### ISSUE TITLE
Storehouse won't work?

### ISSUE THREAD

**Issue by iChippy** [bukson/steampy#101]
I ran "python3 storehouse.py" and then I get this error if you could help that would be great
![2017-11-23 10_48_03-foxxddd gq - putty](https://user-images.githubusercontent.com/23494914/33180786-df478702-d03b-11e7-8f46-27027763dbf5.png)

**Comment by bukson** [comment]
Sure, I have to fix that offer('trade_offer_state') to offer['trade_offer_state']

**Comment by iChippy** [comment]
Well, I changed it to that and now I'm getting this. Sorry I couldn't get back to you quickly I was with my family 
![2017-11-23 17_34_53-foxxddd gq - putty](https://user-images.githubusercontent.com/23494914/33189840-bc50e584-d074-11e7-99a3-fae40fb8ef97.png)

**Comment by crey4fun** [comment]
You changed it to `offer.get['items_to_receive']`. Change it to `offer['items_to_receive']` instead.

**Comment by iChippy** [comment]
Well now I'm just lost 
![image](https://user-images.githubusercontent.com/23494914/33190128-606d1168-d077-11e7-8a26-e7f2f4097c4b.png)

**Comment by bukson** [comment]
It is due to do lack of deploy of the newest version to pip, check please
if it works when you are cloning from github

23 lis 2017 23:54 "iChippy" <notifications@github.com> napisał(a):
