### ISSUE TITLE
How would you load steamguard

### ISSUE THREAD

**Issue by encloinc** [bukson/steampy#106]
The github link provided https://github.com/SMVampire/SteamBotDev/wiki doesnt work anymore

**Comment by crey4fun** [comment]
The steam app does not allow access to the guard file anymore.

You can mod the apk and set the debug mode to True. This will allow you to access the guard file using adb.

**Comment by encloinc** [comment]
is there anyway I could put it in manually everytime I want to run the bot

**Comment by encloinc** [comment]
If thats not possible how would i mod the apk

**Comment by bukson** [comment]
I updated the link of how to obtain Steamguard from mobile.
