### ISSUE TITLE
Trade confirm

### ISSUE THREAD

**Issue by Kupazavr** [bukson/steampy#108]
accept_trade_offer function doesnt work when my items are in the trade offer,i need still manually confirm it on mobile.Can someone help me with it?maybe im doing smth wrong.

**Comment by Dave-Pham** [comment]
I had the same problem. This has been fixed (97d2a983cd23a1a751474975d0e2c7e809a27dfc) but hasn't been released yet. You can edit it in yourself.

**Comment by bukson** [comment]
Ok sorry for delay, I've released that already :) go for version 0.48

**Comment by Kupazavr** [comment]
thx man)
