### ISSUE TITLE
get_trade_receipt should be with login required, in my opinion

### ISSUE THREAD

**Issue by maksimkovalenko** [bukson/steampy#109]
If someone will try to get some receipts using get_trade_receipt without login before it steam will return {"success": False} as a response, so may be you should make this method login required?

**Comment by bukson** [comment]
Yes it is probably true :) Can someone else confirm?

**Comment by vasia123** [comment]
It is true - just checked - https://steamcommunity.com/trade/3089897839390325782/receipt - only return data if logged in account(wrong account and not logging in is not working).

**Comment by bukson** [comment]
Ok I will add required decorator

**Comment by bukson** [comment]
Done
