### ISSUE TITLE
persist session cookies to avoid logging in every time

### ISSUE THREAD

**Issue by foresto** [bukson/steampy#112]
It would be nice if steampy could save session cookies to a file, and load/reuse them instead of logging in every time the calling program is run.

Use case: I'm writing a command line tool that does one operation per execution (list trades, accept a trade, etc). It currently logs in every time it is run, but when I use it more than a few times in a short time period, Steam soft-bans my IP address for logging in too frequently.

I tried pickling client._session.cookies on the first run and then unpickling them into the newly-created client (and skipping login) on subsequent runs, but the client refused to allow this by raising LoginRequired('Use login method first').

**Comment by ThreadShakur** [comment]
Dude you can serialize SteamClient class in file with pickle and load it when you need without relogin. But the session dies every other day

**Comment by bukson** [comment]
So it is a problem, and pickling is solution, probably I should add method serialize and unserializae that pickles and sets variable **was_login_executed** on True

**Comment by ThreadShakur** [comment]
also maybe set "remember_login" : True? It will keep session alive much then 1 day

**Comment by bukson** [comment]
Closing it, because I opened issue #139
