### ISSUE TITLE
To check steam wallet balance

### ISSUE THREAD

**Issue by mihalt** [bukson/steampy#113]
Hello! It would be nice, if your lib allows to check steam wallet balance count on my account. As I understand it isn't this functionality now.

**Comment by bukson** [comment]
Nice feature, I will try to add it

**Comment by mihalt** [comment]
Can you notice me when it will appear?

**Comment by MatyiFKBT** [comment]
Is there any way we can do it in python?

**Comment by bukson** [comment]
Already on master and pypi with version 0.54
