### ISSUE TITLE
Function get_my_inventory can get only 2000 items

### ISSUE THREAD

**Issue by frodo-sa** [bukson/steampy#120]
For now function get_my_inventory can get only 2000 items. I guess a get_partner_inventory too.
I already fixed it for me, but my python skill is low and i wont do pr with that shitty code. 
Maybe someone like @crey4fun, someday,  create good implementation of this. 

p.s. limit is working like "not less". Does not truncate the dictionary

>     @login_required
>     def get_my_inventory(self, game: GameOptions, limit: int = 2000, merge: bool = True) -> dict:
>         url = SteamUrl.COMMUNITY_URL + '/my/inventory/json/' + \
>               game.app_id + '/' + \
>               game.context_id + '/'
>         response_dict = self._session.get(url).json()
>         if len(response_dict['rgInventory']) < limit:
>             while response_dict['more']:
>                 time.sleep(1)
>                 response_dict_temp = self._session.get(url + '?start=' + str(response_dict['more_start'])).json()
>                 response_dict['success'] = response_dict_temp['success']
>                 response_dict['rgInventory'].update(response_dict_temp['rgInventory'])
>                 response_dict['rgDescriptions'].update(response_dict_temp['rgDescriptions'])
>                 response_dict['more'] = response_dict_temp['more']
>                 response_dict['more_start'] = response_dict_temp['more_start']
>                 if len(response_dict['rgInventory']) >= limit:
>                     break
>         if merge:
>             return merge_items_with_descriptions_from_inventory(response_dict, game)
>         return response_dict

**Comment by Opticulex** [comment]
Just change the limit int, simple as that.

**Comment by bukson** [comment]
Now this function uses new api, and you can add upper limit.
