### ISSUE TITLE
Wihtout steamGuard file

### ISSUE THREAD

**Issue by qmmp123** [bukson/steampy#125]
How to use it if account not linked with mobile device?

**Comment by bukson** [comment]
You can use all features that don't required login, read it in documentation. Basically because I want to only support full automated functions of selling, buying (without need of user 2factor input)  you have to link it to your mobile device for steamguard.

For what purpouse you want to use it?

**Comment by qmmp123** [comment]
I want to use for automated trading

**Comment by bukson** [comment]
So unfortunetally you have to link it.
