### ISSUE TITLE
[Question] _fetch_confirmations_page returning "problem loading confirmation page"

### ISSUE THREAD

**Issue by Piero-Bird** [bukson/steampy#132]
I noticed that the _fetch_confirmations_page method was returning a page that says:

"Oh nooooooes! There was a problem loading the confirmations page. Please try your request again later."

Why could this be? I'm unsure if this is a bug and Steam doesn't provide much info or documentation about it. I've confirmed that the session is logged in, device id is made and a confirmation key was created. I hope this question is appropriate here.

Thanks for your time =]

**Comment by bukson** [comment]
I will try to look at it :)

**Comment by ThreadShakur** [comment]
It seems that time on your computer is not correct

**Comment by Piero-Bird** [comment]
> 
> 
> It seems that time on your computer is not correct

Hi, I double checked and my time appears to be correct. I'll investigate some more

**Comment by Piero-Bird** [comment]
Hi, I believe something went wrong with accepting the offer before confirming it. If I understand correctly the confirmations page won't show anything unless the trade is accepted first.

**Comment by Piero-Bird** [comment]
> 
> 
> I will try to look at it :)

Hi, were you able to find anything?

**Comment by Piero-Bird** [comment]
It was the dumbest thing, another library I was using was giving me the wrong steamid64. 

Closing this for good
