### ISSUE TITLE
Session is not alive after a few minutes.

### ISSUE THREAD

**Issue by PetyaT** [bukson/steampy#147]
Hello! I've started using this library recently and came across an issue. I am able to successfully log into my Steam account, accept a trade or fetch my inventory, but after about 10 minutes if I try to use any steampy methods my script rises _TimeoutError: [WinError 10060], ('Connection aborted.', TimeoutError(10060))._

I found a solution: every 2 minutes I use the "is_session_alive" method, but from time to time it also rises errors (not so critical, try/except handes them just fine). 

Is there a more elegant and easy way to keep the session always alive?

**Comment by sap2me** [comment]
Hi, it seems that you have not correct code, because i have no problem with session(without proxy), it is alive for 20 hours at least.
Could you show code?

**Comment by PetyaT** [comment]
Just a quick example code that still rises an error:

`
import time
from steampy.client import SteamClient

steam_api = ''
steam_login = ''
steam_password = ''

def main():
    # logging in
    steam_client = SteamClient(steam_api)
    steam_client.login(steam_login, steam_password, 'Steamguard.maFile')

    # waiting for 10 mintues
    time.sleep(600)

    # checking if the session is still alive
    if steam_client.is_session_alive() == True:
        print('I\'m still alive!')
    else:
        print('I\'m not alive.')

if __name__ == "__main__": 
    main()
`

**Comment by PetyaT** [comment]
Just a quick example script that still rises an error:

``` 
import time
from steampy.client import SteamClient

steam_api = ''
steam_login = ''
steam_password = ''

def main():
    # logging in
    steam_client = SteamClient(steam_api)
    steam_client.login(steam_login, steam_password, 'Steamguard.maFile')

    # waiting for 10 mintues
    time.sleep(600)

    # checking if the session is still alive
    if steam_client.is_session_alive() == True:
        print('I\'m still alive!')
    else:
        print('I\'m not alive.')



if __name__ == "__main__": 
    main() 
```

> 
> 
> Hi, it seems that you have not correct code, because i have no problem with session(without proxy), it is alive for 20 hours at least.
> Could you show code?

**Comment by bukson** [comment]
Hello

Maybe it is due 10 minutes of inactivity, maybe try to call main page or something every minute and then see if it still is an issue.

**Comment by lyp1noff** [comment]
I have the same problem, is_session_alive says false after 10-15 minutes even if i make request every 2 minute. Did anyone find a solution?
