### ISSUE TITLE
get_my_inventory() and accept_trade_offer() don't work

### ISSUE THREAD

**Issue by Vinchezzz** [bukson/steampy#150]
Simple code which prints inventory doesn't work.
![gh_issue](https://user-images.githubusercontent.com/53369056/61993622-26333e00-b077-11e9-941d-ab525677463f.jpg)
![SETM7O0-Ca0](https://user-images.githubusercontent.com/53369056/61993625-29c6c500-b077-11e9-889d-2b8f5b1c7918.jpg)

 Also I have another code which automatically accepts trade offers with some partners but it doesn't work too! It's weird but get_trade_offers_summary() and get_trade_offers() work. I attached only two pics with getting inventory code and cmd with error, if you need my other codes I will attach em too

**Comment by sap2me** [comment]
Hi, the problem is that in the mafile that you are using the steamid key is below than steampy expect. Furthermore the key has incorrect case, so just create a guard file like this:
![example](https://user-images.githubusercontent.com/47041160/61997988-e50c4f80-b0b1-11e9-8ad6-072a09012bb5.PNG)

**Comment by Vinchezzz** [comment]
So I need to create .txt file with these values and write the path to this .txt in 'path_to_steamguard_file' instead of mafile?

**Comment by Vinchezzz** [comment]
I remember I did that but there was a new problem with something about double quotes

**Comment by jjuicecup** [comment]
I also directed it to the mafile with no luck, and creating a text file gives me an error saying it expected double quotes

**Comment by jjuicecup** [comment]
> I also directed it to the mafile with no luck, and creating a text file gives me an error saying it expected double quotes

json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 5 column 1 (char 146)

**Comment by bukson** [comment]
Hello

It should be double quotes and it is case sensitive

**Comment by jjuicecup** [comment]
> Hello
> 
> It should be double quotes and it is case sensitive

Thank you so much for the help, it seems that the template for the text file given includes an extra comma which was causing the error

```
{
    "steamid": "YOUR_STEAM_ID_64",
    "shared_secret": "YOUR_SHARED_SECRET",
    "identity_secret": "YOUR_IDENTITY_SECRET", <<< 
}
```

**Comment by Vinchezzz** [comment]
Thank you guys for help! Good luck!

**Comment by bukson** [comment]
Ok guys I updated the documentation and secrets file to **not** have comma.

Regards
