### ISSUE TITLE
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.steampowered.com/ISteamWebUserPresenceOAuth/Poll/v1

### ISSUE THREAD

**Issue by owoki** [bukson/steampy#154]
Hello i use this code

`import time
from steampy.client import SteamClient
api_key = 'true_key'
steamguard_path = 'true_path'

username = 'true_username'
password = 'true_password'
def main():
    print('This is the chat bot.')
    if not are_credentials_filled():
        print('You have to fill the credentials to run the example')
        print('Terminating bot')
        return
    client = SteamClient(api_key)
    client.login(username, password, steamguard_path)
    print('Bot logged in successfully, polling messages every 10 seconds')
    while True:
        time.sleep(10)
        messages = client.chat.fetch_messages()['received']
        for message in messages:
            client.chat.send_message(message['partner'], "Got your message: " + message['message'])
def are_credentials_filled() -> bool:
    return api_key != '' and steamguard_path != '' and username != '' and password != ''
if __name__ == "__main__":   
    main()`

but i get 

`This is the chat bot.
Bot logged in successfully, polling messages every 10 seconds
Traceback (most recent call last):
  File "index.py", line 36, in <module>
    main()
  File "index.py", line 25, in main
    messages = client.chat.fetch_messages()['received']
  File "C:\Users\musta\AppData\Local\Programs\Python\Python36\lib\site-packages\steampy\chat.py", line 83, in fetch_messages
    events = self.poll_events()
  File "C:\Users\musta\AppData\Local\Programs\Python\Python36\lib\site-packages\steampy\chat.py", line 71, in poll_events
    response = self._api_call(endpoint, params, timeout_ignore=True)
  File "C:\Users\musta\AppData\Local\Programs\Python\Python36\lib\site-packages\steampy\chat.py", line 27, in _api_call
    response.raise_for_status()
  File "C:\Users\musta\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.steampowered.com/ISteamWebUserPresenceOAuth/Poll/v1`

how can i fix it ? can anyone help me?

**Comment by bukson** [comment]
Hello, chat is currently not working, as it got changed to use websockets and I didn't have time to implement those.
