### ISSUE TITLE
json.decoder.JSONDecodeError in raw_decode (client.login)

### ISSUE THREAD

**Issue by gcapedro** [bukson/steampy#158]
`
api_key = 'XXXXXXXXXXXXXXXXXXX'
steamguard_path = '../Steamguard.txt'
username = 'username'
password = 'password'
    
client = SteamClient(api_key)
client.login(username, password, steamguard_path)
`

Getting json.decoder.JSONDecodeError in raw_decode
Using Flask.
Anyone having the same return ?
Could I be doing something wrong here ?

Tkssss

**Comment by CDFN** [comment]
Post full error, please
