### ISSUE TITLE
How to confirm sent trade offer? :/

### ISSUE THREAD

**Issue by Vinchezzz** [bukson/steampy#159]
Hi guys! Pls help me confirm sent trade offer. _confirm_transaction requires trade_offer_id, where can I get it? I use market.csgo.com, so I want to create a bot that will automatically send sold items. I can create trade offer via market api (market uses steam api to send offers) but it has to be confirmed and I have some problems here. I use SDA by Jessecar for my account so I can confirm all transactions without any problems, but help me automate it. Another parts of code work normally.

**Comment by sap2me** [comment]
Hi, write me in telegram, i will help u @andr785

**Comment by matvejs16** [comment]
@sap2me Can you also help me with this?
