### ISSUE TITLE
im fixing the chat.py script 

### ISSUE THREAD

**Issue by movie99** [bukson/steampy#167]
I was wondering which token do I need (token_use_id, or token) to fix the the the out of range problem

**Comment by Gobot1234** [comment]
What do you mean by out of range?
And could you post your code?

**Comment by bukson** [comment]
Hello

The main problem with chat is that it is now working using websockets, and I think the solution should try to use that way of communicating.

If there is a method similar to previous attempts it would be also ok, but I am no aware of it.
