### ISSUE TITLE
Parse price error

### ISSUE THREAD

**Issue by lspvic** [bukson/steampy#174]
```python
price = '11,33 USD'
decimal_price = utils.parse_price(price)
self.assertEquals(decimal_price, decimal.Decimal('11.33'))
```

The `,` in numbers is just a seperator in most cases, not `.` .
For example, the steam price `￥ 4,234.35` is obvisous  4234.35,
but parsed with 4.234~

**Comment by bukson** [comment]
Is this isse somewhat reproducible using steam api?
