### ISSUE TITLE
You can get user inventory more easly

### ISSUE THREAD

**Issue by ThreadShakur** [bukson/steampy#18]
http://steamcommunity.com/profiles/steamid/inventory/json/appid/2
by this url you can get user inventory more easly...

**Comment by bukson** [comment]
Thank you! I will look after it soon

**Comment by bukson** [comment]
What is the difference between it and getmyinventory method

**Comment by LaBlazer** [comment]
/my/inventory/ redirects you to /profiles/steamid/inventory/ anyway, so it can be faster to just call it directly...

**Comment by bukson** [comment]
So this is minor issue but i will try to add it in following days :)

**Comment by ilya-olkhovskij** [comment]
@bukson, before you will add this, check this explanation about new and old endpoint.

https://stackoverflow.com/a/17679641

**Comment by bukson** [comment]
Ok i am implementing it

**Comment by bukson** [comment]
Fixed in release 0.53 already on pip. Thanks!
