### ISSUE TITLE
make_offer_with_url() 

### ISSUE THREAD

**Issue by InsDev** [bukson/steampy#184]
make_offer_with_url() work only if partner in friends. But this should work differently

**Comment by CDFN** [comment]
Not enough informations, post error & code.

**Comment by ldapuser** [comment]
> make_offer_with_url() work only if partner in friends. But this should work differently

your Inventory privacy settings should be set up to Public to use this method. Other way friends only cant send you trade offers. By default Inventory privecy settings is Friends only.

**Comment by GJD0012** [comment]
make_offer_with_url() for item_from_me how list[Asset] create .
but me don't know how work this. 
can you what value  used ?
and error this : 
'assets': [asset.to_dict() for asset in items_from_me],
AttributeError: 'str' object has no attribute 'to_dict' 


make_offer_with_url(items_from_me=List(Asset(asset_id=something,570,1)),...) this not working... ?

**Comment by lexalexa22** [comment]
Hi everyone. Can anybody tell, how should the URL look like? I tried this "https://steamcommunity.com/tradeoffer/SOME_ID", but it doest work.

**Comment by ldapuser** [comment]
Hi, the URL should look like this: 'https://steamcommunity.com/tradeoffer/new/?partner=YOUR_PARTNER_ID&token=YOUR_TOKEN'

> Hi everyone. Can anybody tell, how should the URL look like? I tried this "https://steamcommunity.com/tradeoffer/SOME_ID", but it doest work.
