### ISSUE TITLE
Logging in different way

### ISSUE THREAD

**Issue by CDFN** [bukson/steampy#186]
It'd be great if we could specify secrets ourselves, without using file. Currently we need to specify path to file which contains identity secret, shared secret and steamid.

**Comment by bukson** [comment]
What is the problem with the file that contains all?

**Comment by CDFN** [comment]
Basically there's no problem. It would be easier for me to dockerize my app if we could login by e.g. environment variables. I think we should just specify credentials ourselves, not by file. If you'll like the idea lmk. I could PR it when I'll have time.

**Comment by bukson** [comment]
Sure please do it, i will happily merge it :) Please do not brake backwards compatibility though.
