### ISSUE TITLE
chat.SendMessage not working! 

### ISSUE THREAD

**Issue by haskell-md2** [bukson/steampy#187]
When I try to send a message to a user via Steam, I get an error:
 AppData\Local\Programs\Python\Python38-32\lib\site-packages\requests\models.py", line 829, in raise_for_status
requests.exceptions.HTTPError: 400 Client Error: Bad Request.

`steam_client.chat.send_message("[76561198824394280]","Test")`

**Comment by bukson** [comment]
Yes, chat is now not working, because it is using websockets and neither I nor anybody else had time to rewrite the module yet :)
There is a issue for that: #128

**Comment by haskell-md2** [comment]
Thank you!
