### ISSUE TITLE
Captcha required

### ISSUE THREAD

**Issue by xiaoerbi22** [bukson/steampy#196]
I am using steampy to login steam but I get this error. I print the message {'message': 'Please verify your humanity by re-entering the characters in the captcha.', 'requires_twofactor': False, 'captcha_needed': True}. Where can i verify the captcha? What should i do when i got this message?

**Comment by dustiwe** [comment]
Just change the ip to make the captcha go away

**Comment by NeoBreedZ** [comment]
> Я использую steampy для входа в Steam, но получаю эту ошибку. Я печатаю сообщение {'message': 'Пожалуйста, подтвердите свою человечность, повторно введя символы в капче.', 'requires_twofactor': False, 'captcha_needed': True}. Где я могу проверить капчу? Что мне делать, когда я получил это сообщение?

Steam authorization is saved, just send requests without logging in to your account.
