### ISSUE TITLE
get_my_market_listings() returns empty values

### ISSUE THREAD

**Issue by Anunah9** [bukson/steampy#198]
![1](https://user-images.githubusercontent.com/51327708/105846593-7503c000-5fed-11eb-945c-65dfc14fea7f.png)
![2](https://user-images.githubusercontent.com/51327708/105846613-7d5bfb00-5fed-11eb-9712-9676a79aa453.png)

**Comment by Anunah9** [comment]
The problem was solved by changing the language to English

**Comment by ChekeredList71** [comment]
I can reproduce. Where did you change language?
