### ISSUE TITLE
Получение списка чужих ордеров и продаж предмета / Getting a list of other people's orders and item sales

### ISSUE THREAD

**Issue by Requestedd** [bukson/steampy#200]
Есть ли в steam.py команда для получения списка всех ордеров от других пользователей и всех выставленных предложений на определенный предмет на торговой площадке? 

Does steam.pu have a command to get a list of all orders from other users and all offers for a specific item on the marketplace?

Спасибо.

**Comment by dustiwe** [comment]
На главной странице все методы
