### ISSUE TITLE
How connect proxy in steampy?

### ISSUE THREAD

**Issue by plusf2p** [bukson/steampy#202]

**Comment by Requestedd** [comment]
I am also interested in this topic! As I can see, now the steam.py does not have the function of using a proxy. In addition, I do not yet know how to implement the usual use of a proxy, which is possible in the case of sending post and get requests in the steam.py function, which are just transitions between us and the final requests to steam.

/ Мне тоже интересна эта тема! Как я вижу , сейчас у steam.py нет функции использования прокси. Кроме того , я пока не знаю , как можно внедрить обычное использование прокси , которое возможно в случае отправки запросов post и get в функции steam.py , которые являются лишь переходниками между нами и конечными запросами к стиму.

**Comment by dustiwe** [comment]
change it in the library

![image](https://user-images.githubusercontent.com/65848440/107853542-60159200-6e1f-11eb-9108-712c6628f478.png)

and before login
proxy123 = f'{proxyLog}:{proxyPass}@{proxyIp}' (if with authorization)
steam_client._session.proxies = {'https': str(proxy123)}
steam_client.login(login, password, 'bla_bla.json')

**Comment by Requestedd** [comment]
Let me ask you: is this option also suitable? (this is for private proxies)
```
steamguard_data = {
    "steamid": steamid,
    "shared_secret": shared_secret_key,
    "identity_secret": identity_secret_key
}
steamguard_data = json.dumps(steamguard_data)

steam_client = SteamClient(API_KEY)

steam_client._session.proxies.update({
    "http": "http://login:pass@ip",
    "https": "http://login:pass@ip"
})
```

> change it in the library
> 
> ![image](https://user-images.githubusercontent.com/65848440/107853542-60159200-6e1f-11eb-9108-712c6628f478.png)
> 
> and before login
> proxy123 = f'{proxyLog}:{proxyPass}@{proxyIp}' (if with authorization)
> steam_client._session.proxies = {'https': str(proxy123)}
> steam_client.login(login, password, 'bla_bla.json')

**Comment by dustiwe** [comment]
I don't now
try to run with working and non-working proxies

> Let me ask you: is this option also suitable? (this is for private proxies)
> 
> ```
> steamguard_data = {
>     "steamid": steamid,
>     "shared_secret": shared_secret_key,
>     "identity_secret": identity_secret_key
> }
> steamguard_data = json.dumps(steamguard_data)
> 
> steam_client = SteamClient(API_KEY)
> 
> steam_client._session.proxies.update({
>     "http": "http://login:pass@ip",
>     "https": "http://login:pass@ip"
> })
> ```
> 
> > change it in the library
> > ![image](https://user-images.githubusercontent.com/65848440/107853542-60159200-6e1f-11eb-9108-712c6628f478.png)
> > and before login
> > proxy123 = f'{proxyLog}:{proxyPass}@{proxyIp}' (if with authorization)
> > steam_client._session.proxies = {'https': str(proxy123)}
> > steam_client.login(login, password, 'bla_bla.json')

**Comment by Requestedd** [comment]
Good afternoon, I want to raise this topic again. Is there any official method for connecting a proxy?

**Comment by bukson** [comment]
Official not, If anyone want to add it I will gladly merge it

**Comment by bukson** [comment]
Please rebase you commits onto newest steampy version and make 1 commit out of your changes so it is easier to review

**Comment by bukson** [comment]
Merged
