### ISSUE TITLE
Change price from "you get" to "buyer pays" / Steam commission

### ISSUE THREAD

**Issue by Requestedd** [bukson/steampy#205]
With market methods ( Create Buy Order / Create Sell Order ) we indicate the price of the item
`create_sell_order(asset_id_to_sell, game, "10000")`  where 10000 is what we get after creating the order.
But I have a question.
Is it possible to change the settings so that these 10000 become what the buyer pays (and we ourselves will get about 8697)

If you can't do that, how can you accurately calculate the STEAM commission?

I don’t need to talk about 15 and 13.3 percent.
Steam has some kind of rounding algorithm, in which in one case a formula of the type [ floor((X*1.15)*100)/100 or ceil((X / 1.15) * 100) / 100 ] works properly, in another case you need to add + 1 to the answer, in the third case you need to subtract -1 from the answer. And I don't understand these algorithms.
Therefore, I would like to just immediately put the item up for sale, relying on the prices of competitors, and be able to compete with them.
At the moment, due to the strange commission of the STEAM, it is difficult to lower the price by 1 cent / ruble, because it is impossible to calculate exactly how much I should get so that the price for the buyer is 1 cent / ruble lower than the competitor's price.

Thank you.

**Comment by ldapuser** [comment]
Misunderstanding, who pays fees, can give rise to a myth about a complicated algorithm of calculating fees. 
There are two commisions
 - Steam Transaction Fee - 5%
 - Counter-Strike: Global Offensive Fee - 10%.
And Both of them pays Buyer, not you. 
Example: You create order for item with price 100 usd. Another user buys them and pays 100 usd for your item (this money you'll get) and two fees (see above about fees). In total buyer pays: $100 + $5 + $10. 
13.3% will be if you pay fee, but you don't, so why do you use this figure in your calculations?

**Comment by SlightlyMadMax** [comment]
> Misunderstanding, who pays fees, can give rise to a myth about a complicated algorithm of calculating fees. There are two commisions
> 
> * Steam Transaction Fee - 5%
> * Counter-Strike: Global Offensive Fee - 10%.
>   And Both of them pays Buyer, not you.
>   Example: You create order for item with price 100 usd. Another user buys them and pays 100 usd for your item (this money you'll get) and two fees (see above about fees). In total buyer pays: $100 + $5 + $10.
>   13.3% will be if you pay fee, but you don't, so why do you use this figure in your calculations?

Well, let's say I want to sell a steam trading card from my inventory. I fetch the lowest price of the card and it is, let's say, 1.00 USD. Then I create a sell listing and pass 100 as a price argument. But as a result I get a sell listing for 1.15 USD or smth like that. But that's not what I wanted. So I somehow need to take into account steam commission and its rounding algorithm. I think that was the subject of this issue.

**Comment by BilousVladyslav** [comment]
The easiest way to create these calculations is to simply reuse the algorithm from the Javascript code from `https://community.cloudflare.steamstatic.com/public/javascript/economy_common.js` (`CalculateFeeAmount` and `CalculateAmountToSendForDesiredReceivedAmount` functions) that is used by Steam when a user sells an item from his inventory.

Based on their code, I created the same methods using Python. Here is the PR: #263

**Comment by bukson** [comment]
Merged and deployed
