### ISSUE TITLE
Session is not alive issue

### ISSUE THREAD

**Issue by marshal2111** [bukson/steampy#212]
Hello! Recently I faced a problem when session dies after few minutes or even seconds. For some reason frequent relogin raises "There have been too many login failures from your network in a short time period.  Please wait and try again later." responce from steam, so i had to solve this issue in another way. Today I found out that setting the steamRememberRelogin cookie manually is solution for this problem. In this case client successfully recieves new steamLoginSecure cookie from steam if it was changed. 
In my case code was:
`steam_client._session.cookies.set("steamRememberLogin", cookie_value)`
where cookie_value i got from my browser network menu on steam website .
I hope it will help those guys, who faced same problem. 
Btw I don't know how to fix this issue in the library itself and why remember_login = true in source code doesn't work.

**Comment by MirkevychV** [comment]
THANKS A LOT❤️
