### ISSUE TITLE
TypeError: sequence item 2: expected str instance, int found

### ISSUE THREAD

**Issue by IAmGadget** [bukson/steampy#218]
Error:
``
url = '/'.join([SteamUrl.COMMUNITY_URL, 'inventory', partner_steam_id, game.app_id, game.context_id])
TypeError: sequence item 2: expected str instance, int found
``

Temp fix:
Edit client.py ln. 98
url = '/'.join([SteamUrl.COMMUNITY_URL, 'inventory', partner_steam_id, game.app_id, game.context_id])
->
url = '/'.join([SteamUrl.COMMUNITY_URL, 'inventory', str(partner_steam_id), game.app_id, game.context_id])

I am not a complete expert on this library but my guess is somewhere in your API, string conversion wasnt successful

**Comment by BilousVladyslav** [comment]
This can happen when you pass the `steamid` value as an integer instead of a string in a steamguard file (wich has a json format). According to the example steamguard file provided in the [README](https://github.com/bukson/steampy#usage), you should use the following format:
```json
{
    "steamid": "1234567890",
    "shared_secret": "YOUR_SHARED_SECRET",
    "identity_secret": "YOUR_IDENTITY_SECRET"
}
```
instead of:
```json
{
    "steamid": 1234567890,
    "shared_secret": "YOUR_SHARED_SECRET",
    "identity_secret": "YOUR_IDENTITY_SECRET"
}
```
