### ISSUE TITLE
How to confirm that 'make_offer' was actually made? And how to confirm that the offer was accepted?

### ISSUE THREAD

**Issue by eriktlu** [bukson/steampy#220]
For the first part. I am quite new to python and all of this and I have hard time understanding when the trade offer was sent. Sometime I get no errors but the offer itself was not sent. Is there a way to see the error or something that let's me know the offer was not sent and why?

For the second part. How do I confirm that the trade offer was accepted or denied? I can see get_trade_offer and get_trade_receipt in the documentation but it a little confusing. I want to confirm the trade offer state for specific customers who have got the trade offers.

Again I am bit new to this so I would be very grateful if someone could give me tips or explain the process.

**Comment by armalitedev** [comment]
You could do this:
```
response = steam_client.make_offer([my_asset], [partner_asset], partner_id, 'Test offer')
print(resp)
```
