### ISSUE TITLE
How i can recive market_id, for buy_id

### ISSUE THREAD

**Issue by KokouH** [bukson/steampy#222]
in buy_id i need market_id, but I couldn't find func for this

**Comment by ldapuser** [comment]
Hi, can you add an example, or provide some details?

**Comment by KokouH** [comment]
buy_item(market_name: str, market_id: str, price: int, fee: int, game: GameOptions, currency: Currency = Currency.USD)
steam_client.market.buy_item('AK-47 | Redline (Field-Tested)', '1942659007774983251', 81, 10, GameOptions.CS, Currency.RUB)
this function requires market_id, how can I get it using hashname?

**Comment by KokouH** [comment]
> Hi, can you add an example, or provide some details?

buy_item(market_name: str, market_id: str, price: int, fee: int, game: GameOptions, currency: Currency = Currency.USD)
steam_client.market.buy_item('AK-47 | Redline (Field-Tested)', '1942659007774983251', 81, 10, GameOptions.CS, Currency.RUB)
this function requires market_id, how can I get it using hashname?

**Comment by ldapuser** [comment]
you can get it in two ways i know: 1. using your own scraper of listings of any csgo item, 2. manually on the csgo item page, using browser dev tool.
