### ISSUE TITLE
get_my_market_listings() return empty values

### ISSUE THREAD

**Issue by ChekeredList71** [bukson/steampy#223]
Steps to reproduce:
1. run this code
`from steampy.client import SteamClient
steam_client = SteamClient('MY_API_KEY')
steam_client.login('MY_USERNAME', 'MY_PASSWORD', 'PATH_TO_STEAMGUARD_FILE')
print(steam_client.market.get_my_market_listings())`
2. check output: `{'buy_orders': {}, 'sell_listings': {}}`

OS: Windows 10

**Comment by woctezuma** [comment]
- #198

**Comment by ChekeredList71** [comment]
Yes, I have seen that, and I don't know what softwares language was changed. This is why I have created a new issue.

**Comment by woctezuma** [comment]
In my case, everything works fine. So I don't think the issue is with the function itself.

Maybe try setting the language of the Steam store to English.

**Comment by ChekeredList71** [comment]
Even after changing the client's language, it still gives me an empty list. Maybe because of Steam market limitation I got after changing to Steam Desktop Authenticator?

**Comment by EchoSixHIYA** [comment]
solution A.
  Change ur primary language to english at this site
  [](https://store.steampowered.com/account/languagepreferences/)
solution B.
  If u want keep ur language settings,change the codes at steampy.utils,line 105,107 and 122. Example:
  old line 105:
        ` if "My sell listings" in node.text:`
  new line 105:
        `if "My sell listings" in node.text or "balabala" in node.text:`
  "balabala" is "My sell listings" in ur language, u can get it from steam website.
