### ISSUE TITLE
steam_client.chat.send_message("[ID]", "Message") - requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.steampowered.com/ISteamWebUserPresenceOAuth/Message/v1

### ISSUE THREAD

**Issue by MaxSimpson** [bukson/steampy#225]
Traceback (most recent call last):
  File "steam.py", line 24, in <module>
    client.chat.send_message("[ID]", "This is a message.")
  File "/home/maxsimpson/.local/lib/python3.8/site-packages/steampy/chat.py", line 60, in send_message
    return self._api_call(endpoint, params)
  File "/home/maxsimpson/.local/lib/python3.8/site-packages/steampy/chat.py", line 27, in _api_call
    response.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.steampowered.com/ISteamWebUserPresenceOAuth/Message/v

What is wrong with my code, the login works and the steam ID is valid but I get this error when I try to run the following code:
`steam_client.chat.send_message("[ID]", "This is a message.")`

Any pointers would be much appreciated.

**Comment by woctezuma** [comment]
See:

https://github.com/bukson/steampy#steamchat-methods

The ID should be the **SteamID64**. I think it is an url like: `https://steamcommunity.com/profiles/ID`

**Comment by woctezuma** [comment]
- https://github.com/bukson/steampy/issues/214#issuecomment-945474612
