### ISSUE TITLE
List of buy orders for item

### ISSUE THREAD

**Issue by spchel** [bukson/steampy#226]
Can i get list of buy orders from all people for item. If i can, then how? Thank

**Comment by woctezuma** [comment]
Based [on the README](https://github.com/bukson/steampy#market-methods), I would say no.

**Comment by Rasul11111** [comment]
![image](https://user-images.githubusercontent.com/125439060/219870885-1c4c2603-7169-4c93-b144-e395d9c03750.png)
this is request.
Get item_nameid:
```
import re
item_nameid= re.findall(r'Market_LoadOrderSpread\(\s*(\d+)\s*\)', str(requests.get('paste hrf there').content))[0]
```
