### ISSUE TITLE
create_sell_order method doesn't create an order

### ISSUE THREAD

**Issue by 7CreAtoR7** [bukson/steampy#227]
After successful authorization:
`steam_client = SteamClient('43010E7673E53E31BBEA613F52C6B66A')
steam_client.login(login, password, mafile)`

I try to create sell order:
`asset_id_to_sell = "AUG | Contractor (Minimal Wear)"
sell_response = steam_client.market.create_sell_order(asset_id_to_sell, GameOptions.CS, f"{1000}")`

But there is exception:
`File "C:\Users\...\Python\Python39\lib\site-packages\steampy\market.py", line 108, in create_sell_order
    headers = {'Referer': "%s/profiles/%s/inventory" % (SteamUrl.COMMUNITY_URL, self._steam_guard['steamid'])}
KeyError: 'steamid'`

I tried to change dictionary keys in create_sell_order method in market.py:
instead of 
`headers = {'Referer': "%s/profiles/%s/inventory" % (SteamUrl.COMMUNITY_URL, self._steam_guard['steamid'])}`
where self._steam_guard = 
`self._steam_guard = {'shared_secret': 'NHtV0TB....=', 'serial_number': '13112.....', 'revocation_code': 'R0....', 'uri': 'otpauth://totp/Steam:oryusar?secret=GR5......&issuer=Steam', 'server_time': 154498...., 'account_name': 'ory....', 'token_gid': '2f5da3b55fa3....', 'identity_secret': 'BInlDvsP.....=', 'secret_1': 'by6BLQeRs.....=', 'status': 1, 'device_id': 'android:1cf10.....', 'fully_enrolled': True, 'Session': {'SessionID': '3fdaed3...', 'SteamLogin': '76561.....', 'SteamLoginSecure': '76561198.....', 'WebCookie': 'ED4AA062...', 'OAuthToken': '3d4c...', 'SteamID': 76561198877493969}}`

I changed to:
`headers = {'Referer': "%s/profiles/%s/inventory" % (SteamUrl.COMMUNITY_URL, self._steam_guard['Session']['SteamID'])}`
But now there is 400 status:
`{'success': False, 'message': 'Missing parameters in SellItem request'}`
So how to create sell order correctly?

**Comment by d0nker420** [comment]
Did you manage to resolve the issue? I'm currently experiencing it as well, but only with some items.

**Comment by Spawn944** [comment]
I'm also receiving this error. What is the fix for this? I'm not familiar with python coding. Please help.
{'success': False, 'message': 'Missing parameters in SellItem request'}
