### ISSUE TITLE
donate by bitcoin is unavailable

### ISSUE THREAD

**Issue by songshijun007** [bukson/steampy#229]
it show:"The page you were looking for doesn’t exist", and donate by paypal, not access from china, plz update bitcoin address，thank your work very musch.

**Comment by armalitedev** [comment]
![img](https://user-images.githubusercontent.com/80101791/188277604-372653d1-2267-443e-8d83-a1f8d768f8b1.png)

**Comment by bukson** [comment]
Updated with new adress in plaintext in Readme: 3KrB6B5YRQuSEEZ5EVMAQeGa3SLCFZ76T7
