### ISSUE TITLE
How to check, is session not die?

### ISSUE THREAD

**Issue by ThreadShakur** [bukson/steampy#23]
I user pickle to serialize steamclient class, how to check is session not die?

**Comment by bukson** [comment]
Probably send some simple request that required to be logged in and  check if status is 200 and data is valid

**Comment by bukson** [comment]
Maybe add some method, something called "is_session_alive" passing HEAD request and failing when session is dead(10 minutes?) with appropiate test?

**Comment by ThreadShakur** [comment]
i did yet some method for myself to check, is can bot send offer, becaus i tryed to check is can bot send trade offer by sessionid, but its failed

**Comment by vasia123** [comment]
my_steam_login = "..."
    my_steam_pass = "..."
    my_steam_guard = "..."
    my_steam_api_key = "..."

    need_to_login = False

    # load session
    try:
        session = load_session(sesions_path + steam_login)  # my wrapper for pickle
    except:
        need_to_login = True
        session = requests.session()

    # insert session in SteamClient
    steam_client = SteamClient(my_steam_api_key)
    steam_client._session = session

    # check is logged in or not?
    r = steam_client._session.get('http://steamcommunity.com/')
    if r.text.find(my_steam_login) == -1:
        need_to_login = True

    if need_to_login:
        # login
        print('login...', end='')
        session = requests.session()
        steam_client._session = session
        steam_client.login(my_steam_login, my_steam_pass, my_steam_guard)
        write_session(sesions_path + steam_login, steam_client._session)
        print('ok!')
    else:
        # already logged in
        steam_client.isLoggedIn = True
        steam_client.steam_guard = steampy.guard.load_steam_guard(my_steam_guard)

**Comment by ThreadShakur** [comment]
Nice method

**Comment by bukson** [comment]
So can i close the issue?

**Comment by bukson** [comment]
Maybe one can add method for checking is session alive :)

**Comment by bukson** [comment]
I will write method for this

**Comment by bukson** [comment]
https://github.com/bukson/steampy/pull/32

method isSessionAlive using code from vasia123 snippet. You cen test it, i will deploy it probably this weekend
