### ISSUE TITLE
how to get the captcha img？

### ISSUE THREAD

**Issue by ZangYUzhang** [bukson/steampy#232]
{"success":false,"message":"Please verify your humanity by re-entering the characters in the captcha.","requires_twofactor":false,"captcha_needed":true,"captcha_gid":"3415438848937085157"}

steampy.exceptions.CaptchaRequired: Captcha required
[](url)
How to get the captcha IMG and input the captcha  code？
After got the IMG , I can use the AI recognition picture to convert it into 'str' then input it to finish login

**Comment by ZangYUzhang** [comment]
Traceback (most recent call last):
  File "D:\Python3.10\lib\site-packages\steampy\client.py", line 46, in login
    LoginExecutor(username, password, self.steam_guard['shared_secret'], self._session).login()
  File "D:\Python3.10\lib\site-packages\steampy\login.py", line 22, in login
    self._check_for_captcha(login_response)
  File "D:\Python3.10\lib\site-packages\steampy\login.py", line 89, in _check_for_captcha
    raise CaptchaRequired('Captcha required')
steampy.exceptions.CaptchaRequired: Captcha required

**Comment by bukson** [comment]
Sorry captcha is a blocker for using this in automated matter, maybe some other users can help with showing the ways how you can avoid captcha, but probably changing ip and/or user agent can help.
