### ISSUE TITLE
get_my_inventory, KeyError: 'success'

### ISSUE THREAD

**Issue by Osc44r** [bukson/steampy#233]
Every time when I try to check items in my inventory second time there appears KeyError : 'success'. Could not find what does it mean. When I parse inventory with requests, second, third (and so on) time it is showing full json without any errors. Only while using function from steampy there are problems. Any ideas what should I do?

![image](https://user-images.githubusercontent.com/110410670/191492368-5a2b9957-af6e-4636-89bf-f7e7aade1e96.png)

**Comment by Osc44r** [comment]
I fixed it by making new requests.get call. Then I used merge_items_with_descriptions_from_inventory() and everything is working as it should. I am not removing issue, cuz with lib's functions it is not working

**Comment by Osc44r** [comment]
> @Osc44r Could you please share a few lines of your solution to this. I have the same issue and can't figure out what to do to fix it.

Steam messed something with inventory requests. 95% of requests you will get None now. Afaik using steam api is better to load inventory now, than parsing json. Have not tested it yet. 

Code below used to work few days ago, before steam changes. I bet the limits are temporary, so best option now is to use api and json method combined, or wait.

`
items = requests.get('https://steamcommunity.com/inventory/'+steamID+'/440/2?count=2000',proxies={"https":f"http://{proxy}","http":f"http://{proxy}"}).json()
`

**Comment by BilousVladyslav** [comment]
> Steam messed something with inventory requests. 95% of requests you will get None now. 

Yeah, sometimes Steam doesn't return a `success` key in response, sometimes it just returns `None`. This behavior may be due to issues on the Steam servers or game servers. Either way, it needs to be handled properly.

Here is the fix: #262

**Comment by Osc44r** [comment]
> 

Yeah, but you have to remember also that Steam is returning None, when loaded inventory is private

**Comment by bukson** [comment]
Merged
