### ISSUE TITLE
captcha required

### ISSUE THREAD

**Issue by Osc44r** [bukson/steampy#236]
![image](https://user-images.githubusercontent.com/110410670/196058937-e0633b80-5ad4-49bb-97be-f8a5217a5f41.png)
Any idea how to solve captcha manually or bypass this? In browser there is no captcha.

**Comment by marcu-s** [comment]
Actually there is a captcha in-browser. Once you open many login requests there will be a captcha that you have to solve. Currently the captcha solver does not work.

**Comment by Osc44r** [comment]
> Actually there is a captcha in-browser. Once you open many login requests there will be a captcha that you have to solve. Currently the captcha solver does not work.

Ive tried to force captcha, and it did not appear. All I had was "too many login attempts". Is there any possibility it will disappear after time?

**Comment by marcu-s** [comment]
> > Actually there is a captcha in-browser. Once you open many login requests there will be a captcha that you have to solve. Currently the captcha solver does not work.
> 
> Ive tried to force captcha, and it did not appear. All I had was "too many login attempts". Is there any possibility it will disappear after time?

Hmm, intresting. For me personally I do recieve these captchas on my RDP, might be a geo-location / ip-address issue then; but as stated currently there is no way to solve these issues. My research over time has lead me to belive its a network dropping issue and the best way to solve this is to use a thread to keep the conn alive and if it drops use a proxy.

**Comment by Osc44r** [comment]
> > > Actually there is a captcha in-browser. Once you open many login requests there will be a captcha that you have to solve. Currently the captcha solver does not work.
> > 
> > 
> > Ive tried to force captcha, and it did not appear. All I had was "too many login attempts". Is there any possibility it will disappear after time?
> 
> Hmm, intresting. For me personally I do recieve these captchas on my RDP, might be a geo-location / ip-address issue then; but as stated currently there is no way to solve these issues. My research over time has lead me to belive its a network dropping issue and the best way to solve this is to use a thread to keep the conn alive and if it drops use a proxy.

Well. Is there any schema how to use proxy? Ive tried same as in requests but it is not working :/

**Comment by marcu-s** [comment]
Try using multiple processes to create a connection handler, that worked for me.
