### ISSUE TITLE
get_my_inventory() KeyError: 'steamid'

### ISSUE THREAD

**Issue by Clockknight** [bukson/steampy#238]
When trying to use get_my_inventory(), even when bot has logged in and GameOptions is provided:

![image](https://user-images.githubusercontent.com/34818025/202650438-ab67341c-c261-418a-9b85-ddd6f0867f35.png)

The below error keeps getting raised:

![image](https://user-images.githubusercontent.com/34818025/202650242-94a45a12-1a67-4bad-ade9-41cbfd736a69.png)

As far as I can tell I've setup everything correctly, but the way the error is phrased makes me feel like I should have initialized some value.

**Comment by woctezuma** [comment]
What are the **field names** in your SteamGuard JSON file? Do you have one called `steamid`?

**Comment by Clockknight** [comment]
Yes, it is included.

![image](https://user-images.githubusercontent.com/34818025/202654117-c6f73454-4866-4ab9-87dd-20f4e27957a4.png)

(The file was obtained through Steam Desktop Manager, blocked out the ID, but yes, checking through SteamIO, it is my steam id 64)

The capitalization is different than the one in the error. But even after changing it to "steamid", I got the same KeyError.

**Comment by woctezuma** [comment]
Could you show the full error (red text) when using the correct capitalization `steamid`?

**Comment by woctezuma** [comment]
This should be the solution to your problem:
- https://github.com/bukson/steampy/issues/235

**Comment by Clockknight** [comment]
Ah. Yes, that solved it. 
For what it's worth, it was the exact same error text. But that's probably because of the reason above. Thanks for finding that :)
