### ISSUE TITLE
Error steam.login()

### ISSUE THREAD

**Issue by Onione-Tamiko** [bukson/steampy#241]
![изображение](https://user-images.githubusercontent.com/98662900/213847301-a3a81bba-2dc4-41a8-bb5a-a2d828d00109.png)
![изображение](https://user-images.githubusercontent.com/98662900/213847412-fc910d2e-1a89-4ffc-aafd-f1ab8cad4762.png)

Error after in the line :
steam_client.login(username, password, guard)
The error appeared this morning!

Is there a solution?

**Comment by spchel** [comment]
+

**Comment by Osc44r** [comment]
I think there is problem with this request at login.py
![image](https://user-images.githubusercontent.com/110410670/213859490-753f139c-a596-492b-9da7-3ea1d4dbfaba.png)

**Comment by EmanueleSarte** [comment]
SteamUrl.STORE_URL needs to be changed to SteamUrl.COMMUNITY_URL

**Comment by EmanueleSarte** [comment]
Here 
https://github.com/bukson/steampy/blob/d8af9472526492c572e398778b915218ca316762/steampy/login.py#L52
and here:
https://github.com/bukson/steampy/blob/d8af9472526492c572e398778b915218ca316762/steampy/login.py#L33

SteamUrl.STORE_URL needs to be changed in SteamUrl.COMMUNITY_URL

**Comment by Osc44r** [comment]
> 

Great , it works :). You should pull request this (if you have not)

**Comment by va1ce** [comment]
Can you please tell me if I can use the account proxies in this way?
![image](https://user-images.githubusercontent.com/36516056/213862432-39c8a406-f7ae-4a66-bd77-2c6b90dd03dd.png)
![image](https://user-images.githubusercontent.com/36516056/213862443-2a4a5e7b-f1e0-46d9-85f8-a2fa1e78f1f8.png)

**Comment by Dandelion101** [comment]
[va1ce](https://github.com/va1ce), 
![image](https://user-images.githubusercontent.com/123252000/213871172-bae6c11b-2429-477e-a7c2-7eaeaf0f7884.png)

**Comment by stanislavlysenko0912** [comment]
@EmanueleSarte helped to make a request.
Everything works on a local machine, an error falls inside **_fetch_rsa_params**, **403 Access Denied** from Steam on a remote server. 
Someone came across?

**Comment by wizzzz9** [comment]
@va1ce , u can use my rework with proxy https://github.com/wizzzz9/steampy_rework

**Comment by igreklofrss** [comment]
> Here
> 
> https://github.com/bukson/steampy/blob/d8af9472526492c572e398778b915218ca316762/steampy/login.py#L52
> 
> 
> and here:
> https://github.com/bukson/steampy/blob/d8af9472526492c572e398778b915218ca316762/steampy/login.py#L33
> 
> SteamUrl.STORE_URL needs to be changed in SteamUrl.COMMUNITY_URL

@EmanueleSarte After the error appeared and i understand that '/login/getrsakey/' was not working, I went to look at all requests to Steam in the DevTools Network browser when logging in. I saw that such paths as '/login/getrsakey/' and '/login/dologin' disappeared from requests. When you request them, they redirect to the main page. There is also a new authorization method on the site. I thought that the old method no longer works and began to look and write a new authorization scheme according to the new scheme of the site... How did you know that the old method works? Why did you know that changing the domain would fix the error?

**Comment by EmanueleSarte** [comment]
If you search "getrsakey steam" on Google there are some snippets of code that use steamcommunity as url. I tried itand it worked.

**Comment by Onione-Tamiko** [comment]
@bukson  Yes, but after this change, error 429 appeared.
A few days have passed and she still hasn't disappeared (#246)

**Comment by somespecialone** [comment]
> error 429 appeared. A few days have passed and she still hasn't disappeared

I fell into this problem sometimes (even before url changed) after few unsuccessful tries. It like steam going crazy time after time.
