### ISSUE TITLE
create_buy_order ApiException success: 25, 29

### ISSUE THREAD

**Issue by Dandelion101** [bukson/steampy#242]
`steam_client.market.create_buy_order(Bandit's Boots, 1234, 15, GameOptions.TF2, Currency.RUB)`

When I try to place an order for an item, I get an error
`There was a problem creating the order. Are you using the right currency? success: 25`
or `success: 29`
Who knows what this might be related to?

**Comment by woctezuma** [comment]
> ` success: 25` or `success: 29`

You need to check what that error code means.

**Comment by Dandelion101** [comment]
[woctezuma](https://github.com/woctezuma), I tried to use a debugger and add a `print`
But the debugger didn't show me anything, and the following error comes out when printing
![image](https://user-images.githubusercontent.com/123252000/214037251-46c7a1f1-0836-42fb-9bfb-804859cfd58a.png)
I also tried to print just a response and nothing came out

**Comment by Dandelion101** [comment]
success: 25 - Maximum number of orders
success: 29 - An order for this item already exists

**Comment by woctezuma** [comment]
Okay, so:
- 25 means you have reached the maximum number of buy orders, maybe in count or in value (compared to your Steam Wallet),
- 29 means you already have a buy order for this item, maybe don't put a new one or cancel the old one first.
