### ISSUE TITLE
Where to take games data for GameOptions?

### ISSUE THREAD

**Issue by patap** [bukson/steampy#245]
Hello! 
Whether this api supports all of Steam's games?
Would you explain where I can take IDs for another games? For example for Killing Floor 2 or Pay Day. 
I mean this ids 570 and 2
`DOTA2 = PredefinedOptions('570', '2')`

**Comment by woctezuma** [comment]
AppID and contextID.

https://github.com/bukson/steampy/blob/d8af9472526492c572e398778b915218ca316762/steampy/models.py#L6-L17

**Comment by patap** [comment]
@woctezuma thank you for reply. I saw this :) I asked where I can find these IDs on Steam.
AppID - i found, https://steamcommunity.com/market/search?appid=570 - for example DOTA2, but where to find value for context_id?

**Comment by woctezuma** [comment]
Either try `2` as in:
- https://github.com/alex7kom/node-steam-tradeoffers/issues/154

Or parse the value from the inventory itself. See [StackOverflow](https://stackoverflow.com/a/65943463/376454), etc.
