### ISSUE TITLE
Error "if login_response.json().get('captcha_needed', False)"

### ISSUE THREAD

**Issue by Onione-Tamiko** [bukson/steampy#246]
![изображение](https://user-images.githubusercontent.com/98662900/214789140-101b3e12-099b-4a04-97bc-c6c3362fb377.png)

Such an error occurs after the first (any) account.
The error appeared after corrections in Issues#241.
I'm waiting for a decision or a parting word on what to do...

**Comment by woctezuma** [comment]
It seems the response was `None` instead of JSON. Print `login_response.status_code` if possible.

**Comment by Onione-Tamiko** [comment]
@woctezuma 429

**Comment by woctezuma** [comment]
You got temporarily banned for [`429 Too Many Requests`](https://developer.mozilla.org/en/docs/Web/HTTP/Status/429).

**Comment by szcz761** [comment]
Do you have any idea how to fix it?

**Comment by woctezuma** [comment]
See [StackOverflow](https://stackoverflow.com/q/22786068/376454).
