### ISSUE TITLE
Login Error using SteamGuard file

### ISSUE THREAD

**Issue by maurellio** [bukson/steampy#251]
Does SteamGuard file mean ssfn file? If it so have someone tried using ssfn file for login?

In my case I got an error. I've tried to transform it to base64 but still nothing. 
<img width="522" alt="Снимок экрана 2023-03-13 в 18 29 57" src="https://user-images.githubusercontent.com/109182487/224782414-3abce368-141f-4390-a305-e5fcb0ddd85c.png">
<img width="1095" alt="Снимок экрана 2023-03-13 в 18 23 41" src="https://user-images.githubusercontent.com/109182487/224782405-8be11698-4424-454b-b6ad-4ea30abc945a.png">

I've tried to check my ssfn, it's looks like something wrong with encoding. 
<img width="656" alt="Снимок экрана 2023-03-13 в 18 21 07" src="https://user-images.githubusercontent.com/109182487/224782375-d17c02a5-4b2e-46f0-a196-b8bfb6e065b0.png">

If you have any idea please share it

**Comment by woctezuma** [comment]
This is SteamGuard: https://github.com/bukson/steampy#usage
