### ISSUE TITLE
way to send message 

### ISSUE THREAD

**Issue by wedzyou** [bukson/steampy#26]
hi I want to know if there a function with this api to send messge to a friend in steam by his steamid ??

**Comment by bukson** [comment]
No there isn't, sorry.

**Comment by Zwork101** [comment]
If you want to do that, I suggest using this other steam module [here](https://github.com/ValvePython/steam), but be sure to use the trade system from this library, because the steam modual can't. However, I'm not sure how to send a message by ID, but I can tell you how to make the bot respond to certain messages sent to the bot

**Comment by bukson** [comment]
I will look into implementing this

**Comment by ThreadShakur** [comment]
You can made this func, just use http sniffer (im use fiddler) and emulate this request from steam_client._session.post() with params, which steam use

**Comment by RafGDev** [comment]
I got the sending messages working but it seems that for receiving messages, the steam website uses long polling which probably isn't the best idea. Other implementations seem to establish a TCP connection so you don't have to poll for new messages. Do you suggest we try and implement these tcp connections or what?

**Comment by crey4fun** [comment]
TCP connection sounds fine to me. But it should only establish a connection if a certain function is called first since most bots don't need chat support.

**Comment by bukson** [comment]
Hmm I am not sure but TCP connection on demand seem good. It is hard to say without the code

**Comment by mactepp** [comment]
Check this out #110

**Comment by bukson** [comment]
Resolved! Thanks!
