### ISSUE TITLE
Drop Python 3.5 and 3.6 support

### ISSUE THREAD

**Issue by BilousVladyslav** [bukson/steampy#265]
There are several main reasons for this:

- According to [Python release cycle](https://devguide.python.org/versions/#python-release-cycle), 3.5 and 3.6 versions are in end-of-life state.
- According to [PyPi stats for `steampy`](https://pypistats.org/packages/steampy), Python 3.5 is not used at all, 3.6 almost unused.
- It would be much easier to maintain the library for newer versions of Python.

Once it's approved, I can add metadata about Python version requirements to `setup.py` and implement the use of f-strings (instead of `%` operators and `str.format` calls).

**Comment by BilousVladyslav** [comment]
We can even drop support for Python 3.7 as it will be officially marked as "end-of-life" state in 2 months (2023-06-27).

This will allow us to use even more Python syntax features

**Comment by jiajiaxd** [comment]
It seems that the author is no longer actively maintaining this repository. Can you upload your forked version of Steampy to PyPI? Thank you.

**Comment by woctezuma** [comment]
There was a release last month:
- https://github.com/bukson/steampy/releases/tag/0.80
and a commit to change the donation address to send bitcoins:
- https://github.com/bukson/steampy/commit/98d93cb80db1afec5c1e7adf018020525ca24b68

**Comment by BilousVladyslav** [comment]
> Can you upload your forked version of Steampy to PyPI? 

Thanks for the suggestion, but I don't really want to create another clone of this library. With all due respect to the author, it's hard not to notice that the repository needs more attention, but I certainly wouldn't call it abandoned. 
My goal is to continue the work of all contributors and improve the existing project, which is loved and used by a huge number of developers, despite its problems.

**Comment by bukson** [comment]
Thank you for your support @BilousVladyslav  I am eager to mantain this library, but I am no longer into steam traded, so I will gladly review pull requests and so.

I thught that almost no one is using this library anyway, but knowing it has some community will drive my enthusiasm.

We can change support to version 3.8, but it is a breaking change so I will probably do it with version 1.0

**Comment by bukson** [comment]
After merging #278 I will make a commit with removing chat module, as it is no longer working, but I consider this a breaking change. With this change I will update minimal python to 3.8 and make version 1.0 of steampy

**Comment by bukson** [comment]
Ok so steampy now requires at lest 3.8 python
