### ISSUE TITLE
26 error 

### ISSUE THREAD

**Issue by kalivan666** [bukson/steampy#270]
When sending an exchange, I constantly get this error, although I haven't changed anything in the code and the items exist, please help
![image](https://github.com/bukson/steampy/assets/80101002/6d568a75-aba1-4a82-9405-44b8f93ddb16)

**Comment by woctezuma** [comment]
- #168

**Comment by kalivan666** [comment]
I get an error even when using exactly the same code as in the screenshot from the example
я получаю ошибку даже при использовании точно такого же кода, как на скрине из примера, и все равно получаю данную ошибку
![image](https://github.com/bukson/steampy/assets/80101002/559e2325-d0be-44f9-924b-8207de7e1d08)

**Comment by kalivan666** [comment]
I also found these threads, but they did not help me in any way. I also changed accounts along with links and did not give any results. Items are present, vac is absent, guard protection is present
