### ISSUE TITLE
Captcha required error

### ISSUE THREAD

**Issue by DJTaDJuk** [bukson/steampy#271]
![image](https://github.com/bukson/steampy/assets/114240459/c4911bff-f977-4b06-a0bf-e9dfd07d89fe)
How to fix this problem?
steam_guard.json looks like:
![image](https://github.com/bukson/steampy/assets/114240459/216b2fa6-9d90-492c-bd5d-4f673b458a57)

**Comment by woctezuma** [comment]
- #183 
- #196 
- #236
