### ISSUE TITLE
accept_trade_offer is wrong

### ISSUE THREAD

**Issue by a1063815047** [bukson/steampy#273]
Steam has updated the interface and needs to be fixed. The node-steamcommunity in Github has been fixed. Could the author please fix it? Thank you

**Comment by wolfovik** [comment]
little fix:
[https://github.com/wolfovik/steampy/tree/master](url)

**Comment by p-arbuzov** [comment]
> little fix: [wolfovik@e4ec128](https://github.com/wolfovik/steampy/commit/e4ec128286bf7c94615bccfe1217474cf4dbf86e)
@wolfovik 
you need line `self.id = _id` 
in `Confirmation.__init__`
otherwise not working

**Comment by freezepure** [comment]
`def _send_confirmation(self, confirmation: Confirmation) -> dict:
        params['cid'] = confirmation['id']
        params['ck'] = confirmation['nonce']

    def _get_confirmations(self) -> List[Confirmation]:
        confirmations = []
        confirmations_page = self._fetch_confirmations_page()
        soup = BeautifulSoup(confirmations_page.text, 'html.parser')
        soup = json.loads(str(soup))
        if('conf' in soup):
            confirmations = soup['conf']
        return confirmations

    def _fetch_confirmations_page(self) -> requests.Response:
        response = self._session.get(self.CONF_URL + '/getlist', params=params, headers=headers)


    def _fetch_confirmation_details_page(self, confirmation: Confirmation) -> str:
        tag = 'details' + confirmation['id']
        params = self._create_confirmation_params(tag)
        params['id'] = confirmation['id']
        response = self._session.get(self.CONF_URL + '/detailspage/' + confirmation['id'], params=params)
        return response.json()['html']

    def _create_confirmation_params(self, tag_string: str) -> dict:
        return {'p': android_id,
                'a': self._my_steam_id,
                'k': confirmation_key,
                't': timestamp,
                'm': 'react',
                'tag': tag_string}`

**Comment by freezepure** [comment]
` def _send_confirmation(self, confirmation: Confirmation) -> dict:
        tag = Tag.ALLOW
        params = self._create_confirmation_params(tag.value)
        params['op'] = tag.value,
        params['cid'] = confirmation['id']
        params['ck'] = confirmation['nonce']
        headers = {'X-Requested-With': 'XMLHttpRequest'}
        return self._session.get(self.CONF_URL + '/ajaxop', params=params, headers=headers,proxies={"http":"127.0.0.1:1081","https":"127.0.0.1:1081"}).json()

    def _get_confirmations(self) -> List[Confirmation]:
        confirmations = []
        confirmations_page = self._fetch_confirmations_page()
        soup = BeautifulSoup(confirmations_page.text, 'html.parser')
        soup = json.loads(str(soup))
        if('conf' in soup):
            confirmations = soup['conf']
        return confirmations

 def _fetch_confirmations_page(self) -> requests.Response:
        tag = Tag.CONF.value
        params = self._create_confirmation_params(tag)
        headers = {'X-Requested-With': 'com.valvesoftware.android.steam.community'}
        response = self._session.get(self.CONF_URL + '/getlist', params=params, headers=headers,proxies={"http":"127.0.0.1:1081","https":"127.0.0.1:1081"})
        if 'Steam Guard Mobile Authenticator is providing incorrect Steam Guard codes.' in response.text:
            raise InvalidCredentials('Invalid Steam Guard file')
        return response

    def _fetch_confirmation_details_page(self, confirmation: Confirmation) -> str:
        tag = 'details' + confirmation['id']
        params = self._create_confirmation_params(tag)
        params['id'] = confirmation['id']
        response = self._session.get(self.CONF_URL + '/detailspage/' + confirmation['id'], params=params,proxies={"http":"127.0.0.1:1081","https":"127.0.0.1:1081"})
        return response.text

    def _create_confirmation_params(self, tag_string: str) -> dict:
        timestamp = int(time.time())
        confirmation_key = guard.generate_confirmation_key(self._identity_secret, tag_string, timestamp)
        android_id = guard.generate_device_id(self._my_steam_id)
        return {'p': android_id,
                'a': self._my_steam_id,
                'k': confirmation_key,
                't': timestamp,
                'm': 'react',
                'tag': tag_string}
`

**Comment by freezepure** [comment]
``    def _send_confirmation(self, confirmation: Confirmation) -> dict:
        tag = Tag.ALLOW
        params = self._create_confirmation_params(tag.value)
        params['op'] = tag.value,
        params['cid'] = confirmation['id']
        params['ck'] = confirmation['nonce']
        headers = {'X-Requested-With': 'XMLHttpRequest'}
        return self._session.get(self.CONF_URL + '/ajaxop', params=params, headers=headers).json()

    def _get_confirmations(self) -> List[Confirmation]:
        confirmations = []
        confirmations_page = self._fetch_confirmations_page()
        soup = BeautifulSoup(confirmations_page.text, 'html.parser')
        soup = json.loads(str(soup))
        if('conf' in soup):
            confirmations = soup['conf']
        return confirmations

    def _fetch_confirmations_page(self) -> requests.Response:
        tag = Tag.CONF.value
        params = self._create_confirmation_params(tag)
        headers = {'X-Requested-With': 'com.valvesoftware.android.steam.community'}
        response = self._session.get(self.CONF_URL + '/getlist', params=params, headers=headers)
        if 'Steam Guard Mobile Authenticator is providing incorrect Steam Guard codes.' in response.text:
            raise InvalidCredentials('Invalid Steam Guard file')
        return response

    def _fetch_confirmation_details_page(self, confirmation: Confirmation) -> str:
        tag = 'details' + confirmation['id']
        params = self._create_confirmation_params(tag)
        params['id'] = confirmation['id']
        response = self._session.get(self.CONF_URL + '/detailspage/' + confirmation['id'], params=params)
        return response.text

    def _create_confirmation_params(self, tag_string: str) -> dict:
        timestamp = int(time.time())
        confirmation_key = guard.generate_confirmation_key(self._identity_secret, tag_string, timestamp)
        android_id = guard.generate_device_id(self._my_steam_id)
        return {'p': android_id,
                'a': self._my_steam_id,
                'k': confirmation_key,
                't': timestamp,
                'm': 'react',
                'tag': tag_string}

**Comment by wolfovik** [comment]
> > little fix: [wolfovik@e4ec128](https://github.com/wolfovik/steampy/commit/e4ec128286bf7c94615bccfe1217474cf4dbf86e)
> > @wolfovik
> > you need line `self.id = _id`
> > in `Confirmation.__init__`
> > otherwise not working

I'm sorry. I rushed a bit to share. It's fixed now.
#274

**Comment by Rasul11111** [comment]
confirmations_page always say: {'success': False, 'message': 'Oh nooooooes!', 'detail': 'There was a problem loading the confirmations page. Please try your request again later.'}
Can you help me, please?

**Comment by wolfovik** [comment]
Confirmation no longer has the parameter _id.

**Comment by a1063815047** [comment]
Yes, it's perfect and usable. It's great

**Comment by bukson** [comment]
Will fix after this little merge confict with currencies

**Comment by bukson** [comment]
Fixed
