### ISSUE TITLE
Error in login.py

### ISSUE THREAD

**Issue by AngelDead901** [bukson/steampy#279]
<img width="977" alt="image" src="https://github.com/bukson/steampy/assets/97813570/c1e9ada0-c9d4-422b-bd3a-a5f1a31452fd">
<img width="1012" alt="image" src="https://github.com/bukson/steampy/assets/97813570/db2ee289-f84b-4a81-be82-7e8dfcc9d50e">
Error when I trying to login into steam

**Comment by Edo111k** [comment]
also faced with such a problem, did you manage to find a solution?

**Comment by xoheveras** [comment]
`{
    "steamid": "76*******68",
    "shared_secret": "w*******fU=",
    "identity_secret": "7E*******04="
}`

**Comment by FaMousNoob** [comment]
I don't really understand what is identity is suppose to be, can anyone explain?
also, the shared secret is the Steam Guard code right?

**Comment by makarworld** [comment]
This error related with `._fetch_rsa_params()` func, not with steam guard file.

**Comment by bukson** [comment]
Probably fixed with https://github.com/bukson/steampy/commit/764954e21025424e6cbab5aace921148fb0587ff
