### ISSUE TITLE
How to add up your wallet balance

### ISSUE THREAD

**Issue by Dandelion101** [bukson/steampy#289]
![image](https://github.com/bukson/steampy/assets/123252000/14f6db70-78b5-45ab-b117-33f443bf50a5)
Is there a method to add up or know the pending balance?

**Comment by Rasul11111** [comment]
![image](https://github.com/bukson/steampy/assets/125439060/484996eb-68a6-4e20-b53d-981e723020ba)
in client.py for roubles

**Comment by bukson** [comment]
I think it is fixed in 1.1.1 by setting on_hold  to True in get_wallet_balance
