### ISSUE TITLE
Windows Support

### ISSUE THREAD

**Issue by igeligel** [bukson/steampy#30]
Cool library!

Still there is an issue for Windows users which i noticed today with someone in the discord chat of r/steambot. PyCrypto is not installable in an easy way on Windows so i propose to remove the dependency on the packages and implement a native approach. As reference you could take the C# class from [here](https://bitbucket.org/johnduhart/steamsharp/src/b8e4c85a61437b4e7d247177c04c5b0fad567693/SteamSharp/Authenticator.cs?at=default&fileviewer=file-view-default).

Its just a suggestion and would make a lot of things easier for the Windows folks (i am using ubuntu/windows and .net core, so not likely a python guy).

**Comment by bukson** [comment]
Ok i will think about that, for now i will post workaround on readme page, but i think i can manage to extract crypto and include it in library. 

So people actually using my lbrary :) I am glad, i have no idea how many users it has and i was thinking it was a waste of time

**Comment by bukson** [comment]
So workaround is here:

python -m pip install -U pip
pip install -U setuptools
pip install -U virtualenv Download and install Visual C++ Build tools
http://landinghub.visualstudio.com/visual-cpp-build-tools

pip install steampy

**Comment by Ermans** [comment]
I followed this quick (but dirty) fix: http://stackoverflow.com/questions/24804829/another-one-about-pycrypto-and-paramiko

**Comment by Zwork101** [comment]
Thanks i @igeligel telling bukson! Ya, I was the person asking, you package is amazing, or looks so, I'll try the work around soon, thanks @bukson!

**Comment by ThreadShakur** [comment]
You use little bit functions of pycrypto, maybe you can find some easly to install library and intagrate it in steampy?

**Comment by bukson** [comment]
Are modules hmac and hashlib better, i think they are from standard lib.

**Comment by bukson** [comment]
Sha-1 hmac is available from standard library but rsa is not.

**Comment by bukson** [comment]
I will work on it on branch https://github.com/bukson/steampy/tree/abandon-pycrypto

**Comment by bukson** [comment]
https://github.com/bukson/steampy/pull/31

**Comment by bukson** [comment]
Merged on master, will be deployd soon
