### ISSUE TITLE
Get_my_market_listings() response example

### ISSUE THREAD

**Issue by younes4sami** [bukson/steampy#301]
I need an example about the Get_my_market_listings() response , because my steam account not eligible to put buy orders.
Can some one help me please ?
Thank you.

**Comment by Rasul11111** [comment]
kek {
    'buy_orders': {
        '5829925884': {
            'order_id': '5829925884',
            'quantity': 696,
            'price': '1,12 pуб.',
            'item_name': 'Rugged (Beige) - SKS'
        },
        '5829927433': {
            'order_id': '5829927433',
            'quantity': 410,
            'price': '1,95 pуб.',
            'item_name': 'Combat Pants (Coral)'
        }
    },
    'sell_listings': {
        '4254248208581548979': {
            'listing_id': '4254248208581548979',
            'buyer_pay': '149,24 pуб.',
            'you_receive': '129,79 pуб.',
            'created_on': '7 Feb',
            'need_confirmation': False,
            'description': {
                'currency': 0,
                'appid': 252490,
                'contextid': '2',
                'id': '4201330278575661802',
                'classid': '4734281487',
                'instanceid': '0',
                'amount': '1',
                'status': 2,
                'original_amount': '1',
                'unowned_id': '4202456812836915405',
                'unowned_contextid': '2',
                'background_color': '42413e',
                'icon_url': '6TMcQ7eX6E0EZl2byXi7vaVKyDk_zQLX05x6eLCFM9neAckxGDf7qU2e2gu64OnAeQ7835dY4mLDfCk4nReh8DEiv5dbOq88pLI1RPC9GG8BkfE',
                'icon_url_large': '6TMcQ7eX6E0EZl2byXi7vaVKyDk_zQLX05x6eLCFM9neAckxGDf7qU2e2gu64OnAeQ7835dY4mLDfDY0jhyo8DEiv5dbOq88pLI1RPC9nSuskqY',
                'descriptions': [{
                    'type': 'html',
                    'value': '<span style="color: #FF9800">This is a skin for the <span style="color: #ffdba5">MP5A4</span> item. You will be able to apply this skin at a repair bench or when you craft the item in game.</span><br><br><span style="color: #5098ce">Breaks down into <span style="color: #ffffff">1 x Metal</span></span>'
                }],
                'tradable': 1,
                'actions': [{
                    'link': 'https://steamcommunity.com/sharedfiles/filedetails/?id=2730056984',
                    'name': 'View Workshop Item'
                }],
                'owner_descriptions': [{
                    'value': "You can subscribe to or unsubscribe from this item on the item's Workshop page.",
                    'color': '55FF55'
                }],
                'name': 'Neo Soul MP5',
                'name_color': 'f15840',
                'type': 'Workshop Item',
                'market_name': 'Neo Soul MP5',
                'market_hash_name': 'Neo Soul MP5',
                'commodity': 1,
                'market_tradable_restriction': 7,
                'market_marketable_restriction': 7,
                'marketable': 1,
                'app_icon': 'https://cdn.akamai.steamstatic.com/steamcommunity/public/images/apps/252490/820be4782639f9c4b64fa3ca7e6c26a95ae4fd1c.jpg',
                'owner': 0
            }
        }
    }
}
