### ISSUE TITLE
Login without a API key, is it possible with this library.

### ISSUE THREAD

**Issue by PinguPC** [bukson/steampy#305]
Title.

**Comment by wolfovik** [comment]
Unfortunately, it is not implemented at the moment.

**Comment by PinguPC** [comment]
Do you have any idea how you could do it with editing the library.

**Comment by PinguPC** [comment]
I just need to use this library for the login as i will be using it with no need for an API key.

**Comment by wolfovik** [comment]
> Do you have any idea how you could do it with editing the library.

Yes, you need to track the sequence of requests in the browser's debug mode and then reproduce it in the program. But I can't get to it right now, I need to fix a few more things first :(

**Comment by PinguPC** [comment]
Ah right, thankyou.

**Comment by bukson** [comment]
I am using burpsuite for proxy to track browser request and repeat them with code

**Comment by MaxsonClackson** [comment]
if I understand correctly, you just want to run the library without the API. Just remove the required argument and don't use functions that require an API key. Delete in login.py line 34 or make api_key = '' an empty string. if the question is relevant.
> I just need to use this library for the login as i will be using it with no need for an API key.
