### ISSUE TITLE
Session login issue

### ISSUE THREAD

**Issue by Deihim007** [bukson/steampy#312]
Line 78 of client.py should be `self.steam_guard = {'steamid': self.get_steam_id()}`
Also if you login using session, You'll get error on Line 136 because username is not defined.

**Comment by Deihim007** [comment]
Basically set_login_cookies doesn't work.

**Comment by Deihim007** [comment]
Changing line 78 to `self.steam_guard = {'steamid': str(self.get_steam_id())}` and adding username to SteamClient() solved the issue.

**Comment by bukson** [comment]
Can you make a short pr?

**Comment by Deihim007** [comment]
After 24 hours, when session is expired `get_steam_id` on Line 78 will fail.
`set_login_cookies` should return false if session isn't valid anymore.
