### ISSUE TITLE
get_trade_offer codes

### ISSUE THREAD

**Issue by SamuelKollar** [bukson/steampy#313]
7 if declined
3 if accepted
2 if active
4 if changed
9 if ??? (just got that when sending an offer, the offer wasnt received so probably something like 'Trade offer could not be sent')

Are there any other codes that I hsould know of ? And what is the code when trade offer gets automatically canceled (for example when you send the same item to two people, one accepts it and the other offer gets automatically canceled) ?

**Comment by yesworId** [comment]
https://steamerrors.com/9

**Comment by SamuelKollar** [comment]
![image](https://github.com/bukson/steampy/assets/114473040/ebae2aea-cc22-41a5-a855-9ac1270924f8)
