### ISSUE TITLE
Login without steam guard

### ISSUE THREAD

**Issue by null8tr** [bukson/steampy#315]
Hello my account I trying to login in it don't have steamguard can you help me to login ?

**Comment by MaxsonClackson** [comment]
> Hello my account I trying to login in it don't have steamguard can you help me to login ?

You can't log in to this library without steam guard. The only way is to use authorization via email. Either look for another library, or modify this library. Add an email protocol, write an authorization script in gmail or whatever you use and get an authorization code from email.
