### ISSUE TITLE
Can't buy a certain item on market

### ISSUE THREAD

**Issue by domovenoc** [bukson/steampy#316]
Using steam_client.market.buy_item(item, '5407195803996117793', price=11, fee=15, game=GameOptions.CS)
market_id 100% right, took it from the element code 
error: steampy.exceptions.ApiException: There was a problem buying this item. Message: There was a problem purchasing your item. The listing may have been removed. Refresh the page and try again.

**Comment by OlegBarspinov** [comment]
price = converted_price + converted_fee
fee = converted_fee

**Comment by domovenoc** [comment]
> price = converted_price + converted_fee fee = converted_fee и проверь currency, если рубли: currency: Currency = Currency.RUB
What means "converted"?

**Comment by yesworId** [comment]
Just do it the right way, using your currency. You can find it [here](https://github.com/bukson/steampy/tree/master#currencies):
```python
steam_client.market.buy_item(YOUR_ITEM_NAME, '5407195803996117793', 1100, 10, GameOptions.CS, YOUR_CURRENCY)
 ```

**Comment by yesworId** [comment]
Also important to clarify, you are going to buy only one item using this method. If you want to buy more items with certain price, just use buy order method. 
```python
steam_client.market.create_buy_order('ITEM_NAME', 1100, ITEM_QUANTITY, GameOptions.CS, "YOUR_CURRENCY")
```

**Comment by domovenoc** [comment]
> Просто делайте это правильно, используя свою валюту. Вы можете найти это [здесь](https://github.com/bukson/steampy/tree/master#currencies) :
> 
> ```python
> steam_client.market.buy_item(YOUR_ITEM_NAME, '5407195803996117793', 1100, 10, GameOptions.CS, YOUR_CURRENCY)
> ```
I'm use with currency, not helping

**Comment by OlegBarspinov** [comment]
Price to be in cents, so "100.00"$ should be passed has "10000"

f.e.: if item price on steam 31,86 RUB.
price = 2771 + 415 = 3186
fee = 415
currency = Currency.RUB

**Comment by yesworId** [comment]
> > Просто делайте это правильно, используя свою валюту. Вы можете найти это [здесь](https://github.com/bukson/steampy/tree/master#currencies) :
> > ```python
> > steam_client.market.buy_item(YOUR_ITEM_NAME, '5407195803996117793', 1100, 10, GameOptions.CS, YOUR_CURRENCY)
> > ```
> 
> I'm use with currency, not helping

What's the item name, you're trying to buy?

**Comment by domovenoc** [comment]
> Price to be in cents, so "100.00"$ should be passed has "10000"
> 
> f.e.: if item price on steam 31,86 RUB. price = 2771 + 415 = 3186 fee = 415 currency = Currency.RUB

It helped, thanks
