### ISSUE TITLE
Cannot perform redirects after login, no parameters fetched

### ISSUE THREAD

**Issue by Onione-Tamiko** [bukson/steampy#317]
![изображение](https://github.com/bukson/steampy/assets/98662900/36fbc34e-2400-4d2d-b8ad-5d3969a9d421)

**Comment by yesworId** [comment]
Update steampy library

**Comment by Onione-Tamiko** [comment]
@yesworId   installed the latest 1.1.2

**Comment by Onione-Tamiko** [comment]
My python version 3.8.10 is not supported, upgrading to a newer one solved this problem)
