### ISSUE TITLE
KeyError: 'client_id'

### ISSUE THREAD

**Issue by reasontodie** [bukson/steampy#323]
The code was working and did everything I needed, but just about 30 minutes ago at the next restart it started throwing an error. Maybe someone has encountered and can help? The file with the data from the steam guard is working.

```
def main():
    client = SteamClient(api_key)
    client.login(login, password, 'data/Steamguard.txt')
    is_session_alive = client.is_session_alive()
    print(is_session_alive)
    bot = AutoTrade('sukin sin', client)
    bot.trade_keys()


if __name__ == "__main__":
    main()
    
 Traceback (most recent call last):
  File "C:\main.py", line 41, in <module>
    main()
  File "C:\main.py", line 31, in main
    client.login(login, password, 'data/Steamguard.txt')
  File "C:venv\lib\site-packages\steampy\client.py", line 110, in login
    LoginExecutor(self.username, self._password, self.steam_guard['shared_secret'], self._session).login()
  File "C:venv\lib\site-packages\steampy\login.py", line 38, in login
    self._update_steam_guard(login_response)
  File "C:\venv\lib\site-packages\steampy\login.py", line 116, in _update_steam_guard
    client_id = login_response.json()['response']['client_id']
KeyError: 'client_id'

Process finished with exit code 1

```

**Comment by denghuols** [comment]
I have the same problem with , but i can't resolve it , can you help me? Thank you for your reply

**Comment by LittleRobertTables** [comment]
@denghuols @reasontodie Did either of you find a solution?

**Comment by yesworId** [comment]
> @denghuols @reasontodie Did either of you find a solution?

You can check if session is active, if not use login method. Then you just save cookies to use them later. Currently steampy needs login improvements to make session last longer..

**Comment by yesworId** [comment]
was_login_executed sets as True even when it couldn't login with cookies. The code needs some changes. But is_session_alive still not True, cuz login method was not executed sologin_required func returns error.
