### ISSUE TITLE
how to create empty trade with make_offer_with_url

### ISSUE THREAD

**Issue by Heroslfb** [bukson/steampy#325]
hey. I want to create trade with items only from me. other person don't send anything. but "items_from_them" parameter is required and I cannot make it empty (it cause mistake "'Asset' object is not iterable"). what should I do to create a gift trade with steampy?

may be a dump question but still will be thankful for any help

**Comment by Heroslfb** [comment]
I end up using this code: 

check_trade = steam_client.make_offer_with_url(items_from_me=assetid, items_from_them=[Asset(None,game)], trade_offer_url=url, message=msg)

but steam return this error:
{'strError': 'There was an error sending your trade offer.  Please try again later. (79)'}

**Comment by 1e0n-xx** [comment]
just input [] as parameter

**Comment by Heroslfb** [comment]
thanks. now it's error 26 but at least I saw some issuers with this number

**Comment by Heroslfb** [comment]
> just input [] as parameter

thanks for your help. now I'm creating offers successfully. Is there a way not to use steam guard functions in 'make_offer_with_url'? It creates trade just fine but then return an error 'KeyError: 'identity_secret'' as I didn't setup steamguard for steampy and prefer not to do so/ but anyway I need to get trade id as response

**Comment by 1e0n-xx** [comment]
no way

**Comment by delta325** [comment]
it's not possible to send 2 empty trades from your side to different accounts. you can send the first trade successfully, but the 2nd one will return you error 26. Any fix for that?
