### ISSUE TITLE
How to use SteamGuard.txt with steampy

### ISSUE THREAD

**Issue by Zwork101** [bukson/steampy#33]
I have my secrets and other required pieces of information, however the steamguard.txt file seen to be nonexistent. Can it be added back in?

**Comment by Zwork101** [comment]
Ignore my original question, I figured it out. Though I have a different question now. When trying to login, I'm left with this error:
```python
    return binascii.a2b_base64(s)
binascii.Error: Incorrect padding
```
Now, I don't do much with encryption, so I'm not sure what went wrong, however I think it's because I'm using the text document with the required variables, shared secret, steam id, ect. And not the Steam app file.

**Comment by Ermans** [comment]
I also use a file with the specified variables.
I think you are already following this format:
`{"shared_secret":"your_code_here","identity_secret":"your_identity_here","steamid":"your_steamid_here"}`

Try to check if you have missed some chars in the file, remember it's possible that your codes end with one or more equals ("=") .
Also check if you have the same amount of chars on each field as me:
shared_secret -> 30 chars
identity -> 28 chars
steamid -> 17 chars
I don't know if they need to have the same lenght.

**Comment by Zwork101** [comment]
Ok, I thought  should trim off the ='s and /b's but I shoulda had faith 🤕

**Comment by bukson** [comment]
Is it resolved?

**Comment by Zwork101** [comment]
Yes, correct, thanks for helping 😉

**Comment by bukson** [comment]
Ok, please read docs next time

**Comment by scare313** [comment]
> Ignore my original question, I figured it out. Though I have a different question now. When trying to login, I'm left with this error:
> 
> ```python
>     return binascii.a2b_base64(s)
> binascii.Error: Incorrect padding
> ```
> 
> Now, I don't do much with encryption, so I'm not sure what went wrong, however I think it's because I'm using the text document with the required variables, shared secret, steam id, ect. And not the Steam app file.

Can you please help me How can I use Steamguard.txt file for logging in.
