### ISSUE TITLE
Error with sha1.new

### ISSUE THREAD

**Issue by Zwork101** [bukson/steampy#34]
After accepting the trade, and even receiving the item It traded for, the program exited the loop due to sha1 not having the attribute .new()
```python
hexed_steam_id = sha1.new(steam_id.encode('ascii')).hexdigest()
AttributeError: 'builtin_function_or_method' object has no attribute 'new'
```
So even though it completes the trade, this error still occurs.

**Comment by bukson** [comment]
Damn it must be an error due to new hash function, i am fixing this rirght now

**Comment by bukson** [comment]
fixed, changes on master and on pip
