### ISSUE TITLE
async steampy

### ISSUE THREAD

**Issue by Dandelion101** [bukson/steampy#340]
I need an asynchronous version of the library steampy I know about the existence of https://pypi.org/project/asyncsteampy/#history, but this library has not been supported for a long time. Perhaps someone already has an asynchronous library steampy and you can share it

I need methods: login, create_sell_order, get_wallet_balance, get_my_inventory, get_my_market_listings, create_buy_order

**Comment by Onione-Tamiko** [comment]
use threading module

**Comment by Aarab228** [comment]
> I need an asynchronous version of the library steampy I know about the existence of https://pypi.org/project/asyncsteampy/#history, but this library has not been supported for a long time. Perhaps someone already has an asynchronous library steampy and you can share it
> 
> I need methods: login, create_sell_order, get_wallet_balance, get_my_inventory, get_my_market_listings, create_buy_order

If you found all this stuff, it would be nice if you could share it with me.

**Comment by Dandelion101** [comment]
@Aarab228
I haven't updated the library yet after the Steam update

**Comment by Aarab228** [comment]
> @Aarab228 I haven't updated the library yet after the Steam update


OK, I'll reinstall the library now and try to log in via cookies, and I'll send you the result.

**Comment by Dandelion101** [comment]
@Aarab228 
Sorry for the long wait, I was working on another non-Steam project. The Steampy async library already exists and works great
https://github.com/somespecialone/aiosteampy/tree/master
