### ISSUE TITLE
Steam cookies not working

### ISSUE THREAD

**Issue by denghuols** [bukson/steampy#343]
I logged into steam via my steam username and password, but when I checked my session I found it had expired。
![image](https://github.com/bukson/steampy/assets/52654558/91e15129-2d25-4026-a96f-75dd0f9c70aa)
When I printed the login-related parameters, I found that everything was normal, but the cookie had expired. This situation suddenly appeared today
Thanks for your answer

**Comment by songshijun007** [comment]
me too, cant promise order

**Comment by BuyerProject** [comment]
Now steamcommunity.com store.steampowered.com are separate and each steamLoginSecure works separately

**Comment by wolfovik** [comment]
So we will share too. Everything will be ready soon!

**Comment by crab713** [comment]
just cancel `set_sessionid_cookies()` in LoginExecutor, login(), line 46, can login steamcommunity.com and send trade offer.But I don't know any bad effect with this operation.Waiting for ahthor update.
```
def login(self) -> Session:
        login_response = self._send_login_request()
        if len(login_response.json()['response']) == 0:
            raise ApiException('No response received from Steam API. Please try again later.')
        self._check_for_captcha(login_response)
        self._update_steam_guard(login_response)
        finallized_response = self._finalize_login()
        self._perform_redirects(finallized_response.json())
        # self.set_sessionid_cookies() # cancel this
        return self.session

**Comment by denghuols** [comment]
> just cancel `set_sessionid_cookies()` in LoginExecutor, login(), line 46, can login steamcommunity.com and send trade offer.But I don't know any bad effect with this operation.Waiting for ahthor update.
> 
> ```
> def login(self) -> Session:
>         login_response = self._send_login_request()
>         if len(login_response.json()['response']) == 0:
>             raise ApiException('No response received from Steam API. Please try again later.')
>         self._check_for_captcha(login_response)
>         self._update_steam_guard(login_response)
>         finallized_response = self._finalize_login()
>         self._perform_redirects(finallized_response.json())
>         # self.set_sessionid_cookies() # cancel this
>         return self.session
> ```

This solution is right  , I found the steamcommunity.com and steampowered.com can't share the same sessionId which make the bug.

**Comment by wolfovik** [comment]
I think we shouldn't disable this code. Doing so might disrupt trading operations. It's better to just assign a unique LoginSecure to each domain, similar to what Steam did.

**Comment by wolfovik** [comment]
[https://github.com/bukson/steampy/pull/344](url)

**Comment by wolfovik** [comment]
@ #344

**Comment by jjh4568520** [comment]
> @ #344
> 
> #[49de498](https://github.com/bukson/steampy/pull/344/commits/49de4980ac4d8e100bf8d43a84c05fa6c14ce88c)

create_cookie

**Comment by BuyerProject** [comment]
У вас работает покупка и продажа?

**Comment by wolfovik** [comment]
> Does buying and selling work for you?

Yes, everything is working as before.

**Comment by spsdamn** [comment]
> just cancel `set_sessionid_cookies()` in LoginExecutor, login(), line 46, can login steamcommunity.com and send trade offer.But I don't know any bad effect with this operation.Waiting for ahthor update.
> 
> ```
> def login(self) -> Session:
>         login_response = self._send_login_request()
>         if len(login_response.json()['response']) == 0:
>             raise ApiException('No response received from Steam API. Please try again later.')
>         self._check_for_captcha(login_response)
>         self._update_steam_guard(login_response)
>         finallized_response = self._finalize_login()
>         self._perform_redirects(finallized_response.json())
>         # self.set_sessionid_cookies() # cancel this
>         return self.session
> ```

i used this solution, but i got none response in [response = self._session.post(url, data=params, headers=headers) ](https://github.com/bukson/steampy/blob/a00cf4d47dbede9c86ce493900a66fbcd30b10ad/steampy/client.py#L322C11-L322C11)

**Comment by crab713** [comment]
> > just cancel `set_sessionid_cookies()` in LoginExecutor, login(), line 46, can login steamcommunity.com and send trade offer.But I don't know any bad effect with this operation.Waiting for ahthor update.
> > ```
> > def login(self) -> Session:
> >         login_response = self._send_login_request()
> >         if len(login_response.json()['response']) == 0:
> >             raise ApiException('No response received from Steam API. Please try again later.')
> >         self._check_for_captcha(login_response)
> >         self._update_steam_guard(login_response)
> >         finallized_response = self._finalize_login()
> >         self._perform_redirects(finallized_response.json())
> >         # self.set_sessionid_cookies() # cancel this
> >         return self.session
> > ```
> 
> i used this solution, but i got none response in [response = self._session.post(url, data=params, headers=headers) ](https://github.com/bukson/steampy/blob/a00cf4d47dbede9c86ce493900a66fbcd30b10ad/steampy/client.py#L322C11-L322C11)

recommend to use [wolfovik](https://github.com/wolfovik) solution,https://github.com/bukson/steampy/pull/344.
None response maybe due to your network, I can use this solution send and accept offer few hours ago.

**Comment by kingofthebongo11** [comment]
iam beginner on gh. Dont know how post correctly post recommend. But now login with cookies dont work correctly. I fixed it with next code.

**Comment by xidios** [comment]
> @ #344
> 
> #[49de498](https://github.com/bukson/steampy/pull/344/commits/49de4980ac4d8e100bf8d43a84c05fa6c14ce88c)

I use the library to get cookies for further posts in the discussion. Your solution gives me invalid cookies, since my requests return a 401 status code(
Maybe someone knows how to fix this?

**Comment by vmee** [comment]
> @ #344
> 
> #[49de498](https://github.com/bukson/steampy/pull/344/commits/49de4980ac4d8e100bf8d43a84c05fa6c14ce88c)

buy_item is no work: There are multiple cookies with name, 'sessionid'

**Comment by caramilk** [comment]
> > @ #344
> > #[49de498](https://github.com/bukson/steampy/pull/344/commits/49de4980ac4d8e100bf8d43a84c05fa6c14ce88c)
> 
> I use the library to get cookies for further posts in the discussion. Your solution gives me invalid cookies, since my requests return a 401 status code( Maybe someone knows how to fix this?

Make sure that you are using the 'sessionid' value of domain 'steamcommunity.com' for the trade offer request parameters, there are multiple cookies with name 'sessionid' in the cookiesjar, you have to explicitly choose the value of the correct domain.

**Comment by iWeeDev** [comment]
> @ #344
> 
> #[49de498](https://github.com/bukson/steampy/pull/344/commits/49de4980ac4d8e100bf8d43a84c05fa6c14ce88c)

This fix is not working for me using username, pass and shared_secret to login. 

Any idea how to fix it? This is the traceback:

`Traceback (most recent call last):
  File "C:\Users\Administrator2\AppData\Local\Programs\Python\Python310\lib\site-packages\steampy\client.py", line 110, in login
    LoginExecutor(self.username, self._password, self.steam_guard['shared_secret'], self._session).login()
  File "C:\Users\Administrator2\AppData\Local\Programs\Python\Python310\lib\site-packages\steampy\login.py", line 41, in login
    self.set_sessionid_cookies()
  File "C:\Users\Administrator2\AppData\Local\Programs\Python\Python310\lib\site-packages\steampy\login.py", line 59, in set_sessionid_cookies
    community_cookie = self._create_cookie(name, community_cookie_dic['steamLoginSecure'], community_domain)
AttributeError: 'LoginExecutor' object has no attribute '_create_cookie'`

**Comment by xidios** [comment]
> > @ #344
> > #[49de498](https://github.com/bukson/steampy/pull/344/commits/49de4980ac4d8e100bf8d43a84c05fa6c14ce88c)
> 
> This fix is not working for me using username, pass and shared_secret to login.
> 
> Any idea how to fix it? This is the traceback:
> 
> `Traceback (most recent call last): File "C:\Users\Administrator2\AppData\Local\Programs\Python\Python310\lib\site-packages\steampy\client.py", line 110, in login LoginExecutor(self.username, self._password, self.steam_guard['shared_secret'], self._session).login() File "C:\Users\Administrator2\AppData\Local\Programs\Python\Python310\lib\site-packages\steampy\login.py", line 41, in login self.set_sessionid_cookies() File "C:\Users\Administrator2\AppData\Local\Programs\Python\Python310\lib\site-packages\steampy\login.py", line 59, in set_sessionid_cookies community_cookie = self._create_cookie(name, community_cookie_dic['steamLoginSecure'], community_domain) AttributeError: 'LoginExecutor' object has no attribute '_create_cookie'`

replace self._create_cookie on create_cookie

**Comment by xidios** [comment]
> > > @ #344
> > > #[49de498](https://github.com/bukson/steampy/pull/344/commits/49de4980ac4d8e100bf8d43a84c05fa6c14ce88c)
> > 
> > 
> > I use the library to get cookies for further posts in the discussion. Your solution gives me invalid cookies, since my requests return a 401 status code( Maybe someone knows how to fix this?
> 
> Make sure that you are using the 'sessionid' value of domain 'steamcommunity.com' for the trade offer request parameters, there are multiple cookies with the same name 'sessionid' in the cookiejar, you have to explicitly choose the value of the correct domain.

hmm i tried 
`session.cookies.get_dict("steamcommunity.com")`
but it doesn't work :(

**Comment by iWeeDev** [comment]
> > > @ #344
> > > #[49de498](https://github.com/bukson/steampy/pull/344/commits/49de4980ac4d8e100bf8d43a84c05fa6c14ce88c)
> > 
> > 
> > This fix is not working for me using username, pass and shared_secret to login.
> > Any idea how to fix it? This is the traceback:
> > `Traceback (most recent call last): File "C:\Users\Administrator2\AppData\Local\Programs\Python\Python310\lib\site-packages\steampy\client.py", line 110, in login LoginExecutor(self.username, self._password, self.steam_guard['shared_secret'], self._session).login() File "C:\Users\Administrator2\AppData\Local\Programs\Python\Python310\lib\site-packages\steampy\login.py", line 41, in login self.set_sessionid_cookies() File "C:\Users\Administrator2\AppData\Local\Programs\Python\Python310\lib\site-packages\steampy\login.py", line 59, in set_sessionid_cookies community_cookie = self._create_cookie(name, community_cookie_dic['steamLoginSecure'], community_domain) AttributeError: 'LoginExecutor' object has no attribute '_create_cookie'`
> 
> replace self._create_cookie on create_cookie

I think I did that. This is my current function:

```
def set_sessionid_cookies(self):
  community_domain = SteamUrl.COMMUNITY_URL[8:]
  store_domain = SteamUrl.STORE_URL[8:]
  community_cookie_dic = self.session.cookies.get_dict(domain = community_domain)
  store_cookie_dic = self.session.cookies.get_dict(domain = store_domain)
  for name in ['steamLoginSecure', 'sessionid', 'steamRefresh_steam', 'steamCountry']:
      cookie = self.session.cookies.get_dict()[name]

      if name == 'steamLoginSecure':
          community_cookie = self._create_cookie(name, community_cookie_dic['steamLoginSecure'], community_domain)
          store_cookie = self._create_cookie(name, store_cookie_dic['steamLoginSecure'], store_domain)
      else:
          community_cookie = self._create_cookie(name, cookie, community_domain)
          store_cookie = self._create_cookie(name, cookie, store_domain)

      self.session.cookies.set(**community_cookie)
      self.session.cookies.set(**store_cookie)
```

Am I missing something?

**Comment by xidios** [comment]
> > > > @ #344
> > > > #[49de498](https://github.com/bukson/steampy/pull/344/commits/49de4980ac4d8e100bf8d43a84c05fa6c14ce88c)
> > > 
> > > 
> > > This fix is not working for me using username, pass and shared_secret to login.
> > > Any idea how to fix it? This is the traceback:
> > > `Traceback (most recent call last): File "C:\Users\Administrator2\AppData\Local\Programs\Python\Python310\lib\site-packages\steampy\client.py", line 110, in login LoginExecutor(self.username, self._password, self.steam_guard['shared_secret'], self._session).login() File "C:\Users\Administrator2\AppData\Local\Programs\Python\Python310\lib\site-packages\steampy\login.py", line 41, in login self.set_sessionid_cookies() File "C:\Users\Administrator2\AppData\Local\Programs\Python\Python310\lib\site-packages\steampy\login.py", line 59, in set_sessionid_cookies community_cookie = self._create_cookie(name, community_cookie_dic['steamLoginSecure'], community_domain) AttributeError: 'LoginExecutor' object has no attribute '_create_cookie'`
> > 
> > 
> > replace self._create_cookie on create_cookie
> 
> I think I did that. This is my current function:
> 
> ```
> def set_sessionid_cookies(self):
>   community_domain = SteamUrl.COMMUNITY_URL[8:]
>   store_domain = SteamUrl.STORE_URL[8:]
>   community_cookie_dic = self.session.cookies.get_dict(domain = community_domain)
>   store_cookie_dic = self.session.cookies.get_dict(domain = store_domain)
>   for name in ['steamLoginSecure', 'sessionid', 'steamRefresh_steam', 'steamCountry']:
>       cookie = self.session.cookies.get_dict()[name]
> 
>       if name == 'steamLoginSecure':
>           community_cookie = self._create_cookie(name, community_cookie_dic['steamLoginSecure'], community_domain)
>           store_cookie = self._create_cookie(name, store_cookie_dic['steamLoginSecure'], store_domain)
>       else:
>           community_cookie = self._create_cookie(name, cookie, community_domain)
>           store_cookie = self._create_cookie(name, cookie, store_domain)
> 
>       self.session.cookies.set(**community_cookie)
>       self.session.cookies.set(**store_cookie)
> ```
> 
> Am I missing something?

I replaced self._create_cookie with create_cookie in the code below
```
def set_sessionid_cookies(self):
  community_domain = SteamUrl.COMMUNITY_URL[8:]
  store_domain = SteamUrl.STORE_URL[8:]
  community_cookie_dic = self.session.cookies.get_dict(domain = community_domain)
  store_cookie_dic = self.session.cookies.get_dict(domain = store_domain)
  for name in ['steamLoginSecure', 'sessionid', 'steamRefresh_steam', 'steamCountry']:
      cookie = self.session.cookies.get_dict()[name]

      if name == 'steamLoginSecure':
          community_cookie = create_cookie(name, community_cookie_dic['steamLoginSecure'], community_domain)
          store_cookie = create_cookie(name, store_cookie_dic['steamLoginSecure'], store_domain)
      else:
          community_cookie = create_cookie(name, cookie, community_domain)
          store_cookie = create_cookie(name, cookie, store_domain)

      self.session.cookies.set(**community_cookie)
      self.session.cookies.set(**store_cookie)
```

**Comment by iWeeDev** [comment]
> > > > > @ #344
> > > > > #[49de498](https://github.com/bukson/steampy/pull/344/commits/49de4980ac4d8e100bf8d43a84c05fa6c14ce88c)
> > > > 
> > > > 
> > > > This fix is not working for me using username, pass and shared_secret to login.
> > > > Any idea how to fix it? This is the traceback:
> > > > `Traceback (most recent call last): File "C:\Users\Administrator2\AppData\Local\Programs\Python\Python310\lib\site-packages\steampy\client.py", line 110, in login LoginExecutor(self.username, self._password, self.steam_guard['shared_secret'], self._session).login() File "C:\Users\Administrator2\AppData\Local\Programs\Python\Python310\lib\site-packages\steampy\login.py", line 41, in login self.set_sessionid_cookies() File "C:\Users\Administrator2\AppData\Local\Programs\Python\Python310\lib\site-packages\steampy\login.py", line 59, in set_sessionid_cookies community_cookie = self._create_cookie(name, community_cookie_dic['steamLoginSecure'], community_domain) AttributeError: 'LoginExecutor' object has no attribute '_create_cookie'`
> > > 
> > > 
> > > replace self._create_cookie on create_cookie
> > 
> > 
> > I think I did that. This is my current function:
> > ```
> > def set_sessionid_cookies(self):
> >   community_domain = SteamUrl.COMMUNITY_URL[8:]
> >   store_domain = SteamUrl.STORE_URL[8:]
> >   community_cookie_dic = self.session.cookies.get_dict(domain = community_domain)
> >   store_cookie_dic = self.session.cookies.get_dict(domain = store_domain)
> >   for name in ['steamLoginSecure', 'sessionid', 'steamRefresh_steam', 'steamCountry']:
> >       cookie = self.session.cookies.get_dict()[name]
> > 
> >       if name == 'steamLoginSecure':
> >           community_cookie = self._create_cookie(name, community_cookie_dic['steamLoginSecure'], community_domain)
> >           store_cookie = self._create_cookie(name, store_cookie_dic['steamLoginSecure'], store_domain)
> >       else:
> >           community_cookie = self._create_cookie(name, cookie, community_domain)
> >           store_cookie = self._create_cookie(name, cookie, store_domain)
> > 
> >       self.session.cookies.set(**community_cookie)
> >       self.session.cookies.set(**store_cookie)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Am I missing something?
> 
> I replaced self._create_cookie with create_cookie in the code below
> 
> ```
> def set_sessionid_cookies(self):
>   community_domain = SteamUrl.COMMUNITY_URL[8:]
>   store_domain = SteamUrl.STORE_URL[8:]
>   community_cookie_dic = self.session.cookies.get_dict(domain = community_domain)
>   store_cookie_dic = self.session.cookies.get_dict(domain = store_domain)
>   for name in ['steamLoginSecure', 'sessionid', 'steamRefresh_steam', 'steamCountry']:
>       cookie = self.session.cookies.get_dict()[name]
> 
>       if name == 'steamLoginSecure':
>           community_cookie = create_cookie(name, community_cookie_dic['steamLoginSecure'], community_domain)
>           store_cookie = create_cookie(name, store_cookie_dic['steamLoginSecure'], store_domain)
>       else:
>           community_cookie = create_cookie(name, cookie, community_domain)
>           store_cookie = create_cookie(name, cookie, store_domain)
> 
>       self.session.cookies.set(**community_cookie)
>       self.session.cookies.set(**store_cookie)
> ```

Sorry, I didn´t get you the first time. 

Great, it´s working now. Thank you so much!

**Comment by OlegAlyeynikov** [comment]
I'm using the buy item method from the steampy library. And for the last two days I’ve been receiving this response:

{'message': 'There was a problem purchasing your item. The listing may have been removed. Refresh the page and try again.'}

2024-01-19 18:26:33,196 - my_logger - WARNING - There was a problem buying this item. Message: There was a problem buying this item. Message: There was a problem purchasing your item. The listing may have been removed. Refresh the page and try again.

I tried everything above, nothing worked.
I just can’t cope with this problem, can someone tell me something?

**Comment by xidios** [comment]
My fix for steamcommunity.com

```
def set_sessionid_cookies(self):
        community_domain = SteamUrl.COMMUNITY_URL[8:]
        store_domain = SteamUrl.STORE_URL[8:]
        community_cookie_dic = self.session.cookies.get_dict(domain = community_domain)
        for name in ('steamLoginSecure', 'sessionid', 'steamRefresh_steam', 'steamCountry'):
            cookie = self.session.cookies.get_dict()[name]
            if name in ["sessionid", "steamLoginSecure"]:
                community_cookie = create_cookie(name, community_cookie_dic[name], community_domain)
            else:
                community_cookie = create_cookie(name, cookie, community_domain)
            store_cookie = create_cookie(name, cookie, store_domain)
            self.session.cookies.set(**community_cookie)
            self.session.cookies.set(**store_cookie)
```

**Comment by HappyWaffle566** [comment]
I tried all methods from this issue and I always get one problem: it works through time and I get this error:
KeyError: 'refresh_token'
Is there something I can do?

**Comment by xidios** [comment]
Fixed code for cookies:

in login.py
```
def set_sessionid_cookies(self):
        community_domain = SteamUrl.COMMUNITY_URL[8:]
        store_domain = SteamUrl.STORE_URL[8:]
        community_cookie_dic = self.session.cookies.get_dict(domain = community_domain)
        store_cookie_dic = self.session.cookies.get_dict(domain = store_domain)
        for name in ('steamLoginSecure', 'sessionid', 'steamRefresh_steam', 'steamCountry'):
            cookie = self.session.cookies.get_dict()[name]
            if name in ["steamLoginSecure"]:
                store_cookie = create_cookie(name, store_cookie_dic[name], store_domain)
            else:
                store_cookie = create_cookie(name, cookie, store_domain)

            if name in ["sessionid", "steamLoginSecure"]:
                community_cookie = create_cookie(name, community_cookie_dic[name], community_domain)
            else:
                community_cookie = create_cookie(name, cookie, community_domain)
            
            self.session.cookies.set(**community_cookie)
            self.session.cookies.set(**store_cookie)
```

in client.py (if you use accept trade offer function):
```
    @login_required
    def accept_trade_offer(self, trade_offer_id: str) -> dict:
        trade = self.get_trade_offer(trade_offer_id)
        trade_offer_state = TradeOfferState(trade['response']['offer']['trade_offer_state'])
        if trade_offer_state is not TradeOfferState.Active:
            raise ApiException(f'Invalid trade offer state: {trade_offer_state.name} ({trade_offer_state.value})')

        partner = self._fetch_trade_partner_id(trade_offer_id)
        session_id = self._session.cookies.get_dict("steamcommunity.com")['sessionid']
        accept_url = f'{SteamUrl.COMMUNITY_URL}/tradeoffer/{trade_offer_id}/accept'
        params = {
            'sessionid': session_id,
            'tradeofferid': trade_offer_id,
            'serverid': '1',
            'partner': partner,
            'captcha': '',
        }
        headers = {'Referer': self._get_trade_offer_url(trade_offer_id)}

        response = self._session.post(accept_url, data=params, headers=headers).json()
        if response.get('needs_mobile_confirmation', False):
            return self._confirm_transaction(trade_offer_id)

        return response
```

In general, if you need to restore the functionality of functions, then you need to check calls to self._session.cookies.get_dict and pass the required domain

**Comment by OlegAlyeynikov** [comment]
Fixing the code for cookies as described above does not work for me. 
Using buy_item method i get response:
 {'message': 'There was a problem purchasing your item. The listing may have been removed. Refresh the page and try again.'} 
Has anyone else gotten this?

**Comment by xidios** [comment]
> Fixing the code for cookies as described above does not work for me. Using buy_item method i get response: {'message': 'There was a problem purchasing your item. The listing may have been removed. Refresh the page and try again.'} Has anyone else gotten this?

Try to replace in buy_item method
```
data = {
            'sessionid': self._session_id,
            'currency': currency.value,
            'subtotal': price - fee,
            'fee': fee,
            'total': price,
            'quantity': '1',
        }
```

with

```
data = {
            'sessionid': self._session.cookies.get_dict("steamcommunity.com")['sessionid'],
            'currency': currency.value,
            'subtotal': price - fee,
            'fee': fee,
            'total': price,
            'quantity': '1',
        }
```

**Comment by StarOneButterfly** [comment]
> > Fixing the code for cookies as described above does not work for me. Using buy_item method i get response: {'message': 'There was a problem purchasing your item. The listing may have been removed. Refresh the page and try again.'} Has anyone else gotten this?
> 
> Try to replace in buy_item method
> 
> ```
> data = {
>             'sessionid': self._session_id,
>             'currency': currency.value,
>             'subtotal': price - fee,
>             'fee': fee,
>             'total': price,
>             'quantity': '1',
>         }
> ```
> 
> with
> 
> ```
> data = {
>             'sessionid': self._session.cookies.get_dict("steamcommunity.com")['sessionid'],
>             'currency': currency.value,
>             'subtotal': price - fee,
>             'fee': fee,
>             'total': price,
>             'quantity': '1',
>         }
> ```

it doesn't help, I also get an error: There was a problem purchasing your item. The listing may have been removed. Refresh the page and try again

**Comment by lspeed-v** [comment]
> Fixed code for cookies:
> 
> in login.py
> 
> ```
> def set_sessionid_cookies(self):
>         community_domain = SteamUrl.COMMUNITY_URL[8:]
>         store_domain = SteamUrl.STORE_URL[8:]
>         community_cookie_dic = self.session.cookies.get_dict(domain = community_domain)
>         store_cookie_dic = self.session.cookies.get_dict(domain = store_domain)
>         for name in ('steamLoginSecure', 'sessionid', 'steamRefresh_steam', 'steamCountry'):
>             cookie = self.session.cookies.get_dict()[name]
>             if name in ["steamLoginSecure"]:
>                 store_cookie = create_cookie(name, store_cookie_dic[name], store_domain)
>             else:
>                 store_cookie = create_cookie(name, cookie, store_domain)
> 
>             if name in ["sessionid", "steamLoginSecure"]:
>                 community_cookie = create_cookie(name, community_cookie_dic[name], community_domain)
>             else:
>                 community_cookie = create_cookie(name, cookie, community_domain)
>             
>             self.session.cookies.set(**community_cookie)
>             self.session.cookies.set(**store_cookie)
> ```
> 
> in client.py (if you use accept trade offer function):
> 
> ```
>     @login_required
>     def accept_trade_offer(self, trade_offer_id: str) -> dict:
>         trade = self.get_trade_offer(trade_offer_id)
>         trade_offer_state = TradeOfferState(trade['response']['offer']['trade_offer_state'])
>         if trade_offer_state is not TradeOfferState.Active:
>             raise ApiException(f'Invalid trade offer state: {trade_offer_state.name} ({trade_offer_state.value})')
> 
>         partner = self._fetch_trade_partner_id(trade_offer_id)
>         session_id = self._session.cookies.get_dict("steamcommunity.com")['sessionid']
>         accept_url = f'{SteamUrl.COMMUNITY_URL}/tradeoffer/{trade_offer_id}/accept'
>         params = {
>             'sessionid': session_id,
>             'tradeofferid': trade_offer_id,
>             'serverid': '1',
>             'partner': partner,
>             'captcha': '',
>         }
>         headers = {'Referer': self._get_trade_offer_url(trade_offer_id)}
> 
>         response = self._session.post(accept_url, data=params, headers=headers).json()
>         if response.get('needs_mobile_confirmation', False):
>             return self._confirm_transaction(trade_offer_id)
> 
>         return response
> ```
> 
> In general, if you need to restore the functionality of functions, then you need to check calls to self._session.cookies.get_dict and pass the required domain
> 
> I only tested the code for steamcommunity, so let me know if anything doesn't work

Seems everything works fine, thank you

**Comment by HappyWaffle566** [comment]
Had somebody found a solution to KeyError: 'refresh_token'?

**Comment by Dandelion101** [comment]
> Had somebody found a solution to KeyError: 'refresh_token'?

The KeyError: 'refresh_token' exception occurs when you have exhausted all your login attempts. They are usually updated after 12 hours

Your question is not related to the topic of this question https://github.com/bukson/steampy/issues/343, next time create a new question

**Comment by Aarab228** [comment]
I updated the login.py file to the above commit from @xidios  but authorization still doesn't work as well as purchases in steam)
Does anyone know what this is related to? Every time I try to log in to my account cookies are created, and when I try to log in again authorization via cookies doesn't work with the error "Invalid steam_id: None".

**Comment by SiSiska** [comment]
client.py 
```
    def _get_session_id(self) -> str:
        return self._session.cookies.get_dict("steamcommunity.com")['sessionid']
```
