### ISSUE TITLE
can not connect steamguard file

### ISSUE THREAD

**Issue by negstek** [bukson/steampy#347]
Hi here, I followed the readme tutorials to try to import the steamguard file from an android emulator. The only file files that looks usefull after steam installation and connection is a:
```/data/data/com.valvesoftware.android.steamcommunity/files/PersistedInstallation.XXXXX___BIG_UID___XXXXX.json```

It contains json with these informations:

```
{
    "Fid": "XXXXXXXXXX",
    "Status": 3,
    "AuthToken": "XXXXXXXXXX",
    "RefreshToken": "XXX"
    "TokenCreationEpochInSecs": 1705836030,
    "ExpiresInSecs": 604800
}
```

I cant find anything that looks like:

```
{
    "steamid": "YOUR_STEAM_ID_64",
    "shared_secret": "YOUR_SHARED_SECRET",
    "identity_secret": "YOUR_IDENTITY_SECRET"
}
```

may someione help me plz ?

**Comment by Dandelion101** [comment]
You need to take the data from mafile it looks like this:
`{"shared_secret":"","serial_number":"","revocation_code":"","uri":"","server_time":123,"account_name":"","token_gid":"","identity_secret":"","secret_1":"","status":1,"device_id":"","fully_enrolled":true,"Session":{"SessionID":"","SteamLoginSecure":"","SteamID":123}}`

To create a mafile file, use an application that allows you to do this
I'm using https://github.com/TradeOnSolutions/Steam-Desktop-Authenticator
After logging into your account, a file will be created that will contain all the data you need
