### ISSUE TITLE
Bug - Expected Trade confirmation

### ISSUE THREAD

**Issue by Zwork101** [bukson/steampy#35]
After adding the updated version of steampy, the bot accepted the trade, but stopped the loop due to an expected trade confirmation:
```python
raise ConfirmationExpected
steampy.confirmation.ConfirmationExpected
```
The items, like last time, went through successfully, however still created this error

**Comment by bukson** [comment]
Ok where you trading with your friend, this exception says that it expected confirmation but there wasn't any, could go give me more details

**Comment by Zwork101** [comment]
Sure. I had a trade set for 1 item for 2 refined metal. I gave the bot 2 refined and it gave me the item. However, In doing so, it raised that Error. Though, I'm starting to believe this is because I also have SDA running, do you think SDA confirmed the trade, and the program tried to confirm it but couldn't due to it already being confirmed?

**Comment by bukson** [comment]
yep it could be that, i dont know what is sda but my program tries to confirm and raise exception when there is no confirmation

**Comment by Ermans** [comment]
I have the same problem when I use my phone to confirm other things.
If I refresh the confirmation page on my phone the next bot confirmation will probably fail. But I think this is a steam problem.

**Comment by bukson** [comment]
Ok so do you guys proposing any solution?

Its an exception, it can be catched, i used this library on seprate account that i don't manually click

**Comment by Zwork101** [comment]
Can you make it a warning instead by importing warning? That way it wouldn't stop the loop Or, possibly have it check if the trade is still existent, before raising an error

**Comment by Ermans** [comment]
My workaround it's just a try catch: I try to make an offer, if the confirmation fails I just retry it.

**Comment by Zwork101** [comment]
Adding onto @Ermans, after like, 5-10 retry, Have it return the warning, `Unable to secure confirmation <Trade ID>`?

**Comment by bukson** [comment]
Warnings are bad pattern, tends to be ignored.
I would agree to use Ermans solutions and use try catch.
Closing issue

**Comment by Zwork101** [comment]
When is this going to be implemented?

**Comment by bukson** [comment]
Use try catch in your code, that was the solution. Exception is just better warning, you can't ignore it :)

**Comment by Zwork101** [comment]
Ah, ok, thx
