### ISSUE TITLE
Can't create trade offer using steam_guard.json & trade_url

### ISSUE THREAD

**Issue by VlexWest** [bukson/steampy#357]
*UPDATE: 
I applied the changes from [PR](https://github.com/bukson/steampy/pull/344) and now it's logging in, but if I try to create a trade `make_offer_with_url()` I get Response 401 Unauthorized...

Now I need help with it, so would appreciate any help. :')

Code:
``` python
# Code to login
# ...
# ...

# Returns "None" because receiving 401 Unauthorized
game = GameOptions.CS
my_items = steam_client.get_my_inventory(game)
my_first_item = next(iter(my_items.values()))
my_asset = Asset(my_first_item['id'], game)
x = steam_client.make_offer_with_url(items_from_me=[my_asset],
                                     items_from_them=[],
                                     trade_offer_url="https://steamcommunity.com/tradeoffer/new/?partner=150059734&token=m3TeWVQA",
                                     message="test message")
```

here's a screenshot from steampy/client.py with debug values
![image](https://github.com/bukson/steampy/assets/59747331/472a9a42-557e-4200-9239-fb8525a52979)

--

Hello everyone,

somehow I can't login to steam using my steam_guard.json.

Do someone know how to fix it?
Am I doing something wrong?

test.py
``` python
from steampy.client import SteamClient

steam_id = 123456789
api_key = "xxxxxxxx"
steam_client = SteamClient(api_key=api_key)

# Can read from file
with open(file="steam_guard.json", mode="r") as x:
    print(x.read())

steam_client.login(username="xxxxx", password="xxxxx",
                   steam_guard=f"steam_guard.json")

# Returns False
print(steam_client.is_session_alive())
```

steam_guard.json
``` json
{
  "steamid": "123456789",
  "shared_secret": "xxxxxxxxx",
  "identity_secret": "xxxxxxxxx"
}
```

Thanks in advance!

**Comment by AlexTwice** [comment]
[this worked](https://github.com/bukson/steampy/issues/343#issuecomment-1900770882) for me, thanks to [@xidios](https://github.com/xidios)

**Comment by Aarab228** [comment]
show "code to login" or use login method and send a request for the function to create an ofer immediately after the login

def login:
***login
***login
***is_session_alive()
if is_session_alive == True:
   main()

def main():
***create order witg your params

**Comment by ExpiredMeteor6** [comment]
> *UPDATE: I applied the changes from [PR](https://github.com/bukson/steampy/pull/344) and now it's logging in, but if I try to create a trade `make_offer_with_url()` I get Response 401 Unauthorized...
> 
> Now I need help with it, so would appreciate any help. :')
> 
> Code:
> 
> ```python
> # Code to login
> # ...
> # ...
> 
> # Returns "None" because receiving 401 Unauthorized
> game = GameOptions.CS
> my_items = steam_client.get_my_inventory(game)
> my_first_item = next(iter(my_items.values()))
> my_asset = Asset(my_first_item['id'], game)
> x = steam_client.make_offer_with_url(items_from_me=[my_asset],
>                                      items_from_them=[],
>                                      trade_offer_url="https://steamcommunity.com/tradeoffer/new/?partner=150059734&token=m3TeWVQA",
>                                      message="test message")
> ```
> 
> here's a screenshot from steampy/client.py with debug values ![image](https://private-user-images.githubusercontent.com/59747331/301255701-472a9a42-557e-4200-9239-fb8525a52979.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgyMDIwMDAsIm5iZiI6MTcwODIwMTcwMCwicGF0aCI6Ii81OTc0NzMzMS8zMDEyNTU3MDEtNDcyYTlhNDItNTU3ZS00MjAwLTkyMzktZmI4NTI1YTUyOTc5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE3VDIwMjgyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZjMzc3Mzc3M2M2NWQ1YzgwMWQxOTc3NDhlNDhhNGMyODNmYmNmNDQ1OGZjMzMyNzg3ZTNjYjZkYjY5Y2VjZjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5p8_IKlNqTgSu7DiXO2tUXp-6zDtENvTm0nz8snbT6Q)
> 
> --
> 
> Hello everyone,
> 
> somehow I can't login to steam using my steam_guard.json.
> 
> Do someone know how to fix it? Am I doing something wrong?
> 
> test.py
> 
> ```python
> from steampy.client import SteamClient
> 
> steam_id = 123456789
> api_key = "xxxxxxxx"
> steam_client = SteamClient(api_key=api_key)
> 
> # Can read from file
> with open(file="steam_guard.json", mode="r") as x:
>     print(x.read())
> 
> steam_client.login(username="xxxxx", password="xxxxx",
>                    steam_guard=f"steam_guard.json")
> 
> # Returns False
> print(steam_client.is_session_alive())
> ```
> 
> steam_guard.json
> 
> ```json
> {
>   "steamid": "123456789",
>   "shared_secret": "xxxxxxxxx",
>   "identity_secret": "xxxxxxxxx"
> }
> ```
> 
> Thanks in advance!

Hey Alex, did you manage to get sending trade offers working? im having a similar issue except getting at error 500 response
