### ISSUE TITLE
make_offer_with_url error

### ISSUE THREAD

**Issue by ThreadShakur** [bukson/steampy#36]
it always return None now... maybe you set cookie with login not correct?

**Comment by Ermans** [comment]
With the 0.33v, if I run the test "test_make_offer_url" it works. (yeah, the first attempt raised a ConfirmationError, but the second attempt worked).

**Comment by bukson** [comment]
So ThreadShakur, did you test it on 0.32v, i will look on it tomorrow.

So Ermans, tests dont work sometimes?

**Comment by ThreadShakur** [comment]
> So Ermans, tests dont work sometimes?

If this works from second attempt, then set_sessionid_cooie don't help

**Comment by Ermans** [comment]
About the confirmation error, we have discussed about it here: #35 it's the same "problem"

ThreadShakur are you sure the items you are trading are tradable?

**Comment by ThreadShakur** [comment]
> ThreadShakur are you sure the items you are trading are tradable?

Sure, i've remove scring with setting up session cookie and now it works

**Comment by bukson** [comment]
scring?

**Comment by Ermans** [comment]
I think he meant script.
If so, can you please copy and paste the script before and after your changes?

**Comment by ThreadShakur** [comment]
> Sure, i've remove string with setting up session cookie and now it works

But with second attempt, when steam setup cookie

**Comment by ThreadShakur** [comment]
Wow now it works correctly, maybe it was steam lags... Close this tab man
