### ISSUE TITLE
Unable to sell of buy items

### ISSUE THREAD

**Issue by volodymyrzuyev** [bukson/steampy#369]
When copying the example code from the README, i get this response `{'success': False, 'message': 'There was a problem listing your item. Refresh the page and try again.'}`

```python 
with SteamClient('api_key', 'usename', 'password', 'steamguard.txt') as client:
    asset_id_to_sell = '35927051632'
    game = GameOptions.CS
    sell_response = client.market.create_sell_order(asset_id_to_sell, game, "10000")
    print(sell_response)
```

**Comment by Hodackin** [comment]
Make sure that:
* item with the assetid is present in your inventory
* item with the assetid is marketable
* your local version of steampy is up to date

**Comment by Hodackin** [comment]
The same error occurs if cookies are not set properly. Ensure that ur version of steampy is up to date. 
Have you made any changes to the _set_sessionid_cookies method in steampy/login.py?

**Comment by volodymyrzuyev** [comment]
No i have now. I just pulled steampy from pip

**Comment by Hodackin** [comment]
If the Pypi version is different from the current repo version, this should help.
