### ISSUE TITLE
[Discussion] About the Steam Market

### ISSUE THREAD

**Issue by Ermans** [bukson/steampy#37]
(talking to bukson the author of this library) 
I have made for myself some function to handle the Steam Market.
I'm talking about creating a buy order or a sell listing and removing them (confirmation with steamguard included).

Is it your plan to have them in this library?

I can make a pull request if you agree, I just need to make the functions more general because now are crafted right for my code and to make some tests.

**Comment by Ermans** [comment]
Also to back up this #17

**Comment by bukson** [comment]
Yes pls, make pull request, i will be glad

**Comment by Ermans** [comment]
I'll make that probably today or tomorrow

**Comment by bukson** [comment]
Merged

**Comment by VVILD** [comment]
@Ermans can you please update the readme for market methods examples . they are still using SteamClient class instead of SteamMarket . i am myself having trouble figuring out what to pass in SteamMarket() parenthesis .

**Comment by bukson** [comment]
Ok sorry i will update it soon

**Comment by Ermans** [comment]
You should not create a SteamMarket class, there is a field in the SteamClient class to use the market:
client.market.create_buy_order(...) 
but you need to login with the steamclient before to use it.
There are some example inside the test folder on test_client.py

**Comment by bukson** [comment]
Updated docs on master
