### ISSUE TITLE
create_buy_order not working

### ISSUE THREAD

**Issue by jjh4568520** [bukson/steampy#371]
```python
market_hash_name = "G3SG1 | Dream Glade (Minimal Wear)"
buy_quantity = 1
buy_price = 20
cs = GameOptions.CS
currency = Currency.USD
state = client.market.create_buy_order(market_name=market_hash_name, quantity=buy_quantity,
                                       price_single_item=buy_price,
                                       game=cs, currency=currency)
``` 
I have tried the following methods to fix it

```python
def create_buy_order(
    self,
    market_name: str,
    price_single_item: str,
    quantity: int,
    game: GameOptions,
    currency: Currency = Currency.USD,
) -> dict:
    data = {
        'sessionid': self._session.cookies.get_dict("steamcommunity.com")['sessionid'],  # <<------
        'currency': currency.value,
        'appid': game.app_id,
        'market_hash_name': market_name,
        'price_total': str(Decimal(price_single_item) * Decimal(quantity)),
        'quantity': quantity,
    }
``` 
and

```python
def set_sessionid_cookies(self):
    community_domain = SteamUrl.COMMUNITY_URL[8:]
    store_domain = SteamUrl.STORE_URL[8:]
    community_cookie_dic = self.session.cookies.get_dict(domain=community_domain)
    store_cookie_dic = self.session.cookies.get_dict(domain=store_domain)
    for name in ('steamLoginSecure', 'sessionid', 'steamRefresh_steam', 'steamCountry'):
        cookie = self.session.cookies.get_dict()[name]
        if name in ["steamLoginSecure"]:
            store_cookie = create_cookie(name, store_cookie_dic[name], store_domain)
        else:
            store_cookie = create_cookie(name, cookie, store_domain)

        if name in ["sessionid", "steamLoginSecure"]:
            community_cookie = create_cookie(name, community_cookie_dic[name], community_domain)
        else:
            community_cookie = create_cookie(name, cookie, community_domain)

        self.session.cookies.set(**community_cookie)
        self.session.cookies.set(**store_cookie)
``` 
create_buy_order
response = self._session.post(f'{SteamUrl.COMMUNITY_URL}/market/createbuyorder/', json=data, headers=headers)
print(response.status_code)   ==  400
print(response.text)    ==  [ ]

but cancel_buy_order is working!!!

I don't know why

**Comment by jjh4568520** [comment]
> It seems that steampy does not send bill address?

My billing address has been saved in the market

**Comment by Aarab228** [comment]
try use all this fixes

client.py

def set_login_cookies(self, cookies: dict) -> None:
        self._session.cookies.update(cookies)
        self.was_login_executed = True
        if self.steam_guard is None:
            self.steam_guard = {'steamid': str(self.get_steam_id())}
        self.market._set_login_executed(self.steam_guard, self._get_session_id())


 @login_required
    def accept_trade_offer(self, trade_offer_id: str) -> dict:
        trade = self.get_trade_offer(trade_offer_id)
        trade_offer_state = TradeOfferState(trade['response']['offer']['trade_offer_state'])
        if trade_offer_state is not TradeOfferState.Active:
            raise ApiException(f'Invalid trade offer state: {trade_offer_state.name} ({trade_offer_state.value})')

        partner = self._fetch_trade_partner_id(trade_offer_id)
        session_id = self._session.cookies.get_dict("steamcommunity.com")['sessionid']
        accept_url = f'{SteamUrl.COMMUNITY_URL}/tradeoffer/{trade_offer_id}/accept'
        params = {
            'sessionid': session_id,
            'tradeofferid': trade_offer_id,
            'serverid': '1',
            'partner': partner,
            'captcha': '',
        }
        headers = {'Referer': self._get_trade_offer_url(trade_offer_id)}

        response = self._session.post(accept_url, data=params, headers=headers).json()
        if response.get('needs_mobile_confirmation', False):
            return self._confirm_transaction(trade_offer_id)

        return response

--------------------------------------------------------------------------------------------------------------------------

login.py

def set_sessionid_cookies(self):
        community_domain = SteamUrl.COMMUNITY_URL[8:]
        store_domain = SteamUrl.STORE_URL[8:]
        community_cookie_dic = self.session.cookies.get_dict(domain = community_domain)
        store_cookie_dic = self.session.cookies.get_dict(domain = store_domain)
        for name in ('steamLoginSecure', 'sessionid', 'steamRefresh_steam', 'steamCountry'):
            cookie = self.session.cookies.get_dict()[name]
            if name in ["steamLoginSecure"]:
                store_cookie = create_cookie(name, store_cookie_dic[name], store_domain)
            else:
                store_cookie = create_cookie(name, cookie, store_domain)

            if name in ["sessionid", "steamLoginSecure"]:
                community_cookie = create_cookie(name, community_cookie_dic[name], community_domain)
            else:
                community_cookie = create_cookie(name, cookie, community_domain)
            
            self.session.cookies.set(**community_cookie)
            self.session.cookies.set(**store_cookie)

--------------------------------------------------------------------------------------------------------------------------

market.py

data = {
            #'sessionid': self._session.cookies.get_dict("steamcommunity.com")['sessionid'],
            'sessionid': self._session_id,
            'currency': currency.value,
            'appid': game.app_id,
            'market_hash_name': market_name,
            'price_total': str(Decimal(price_single_item) * Decimal(quantity)),
            'quantity': quantity,
        }

**Comment by Aarab228** [comment]
> > try use all this fixes
> > ```python
> > client.py
> > 
> > def set_login_cookies(self, cookies: dict) -> None:
> >         self._session.cookies.update(cookies)
> >         self.was_login_executed = True
> >         if self.steam_guard is None:
> >             self.steam_guard = {'steamid': str(self.get_steam_id())}
> >         self.market._set_login_executed(self.steam_guard, self._get_session_id())
> > 
> > 
> >  @login_required
> >     def accept_trade_offer(self, trade_offer_id: str) -> dict:
> >         trade = self.get_trade_offer(trade_offer_id)
> >         trade_offer_state = TradeOfferState(trade['response']['offer']['trade_offer_state'])
> >         if trade_offer_state is not TradeOfferState.Active:
> >             raise ApiException(f'Invalid trade offer state: {trade_offer_state.name} ({trade_offer_state.value})')
> > 
> >         partner = self._fetch_trade_partner_id(trade_offer_id)
> >         session_id = self._session.cookies.get_dict("steamcommunity.com")['sessionid']
> >         accept_url = f'{SteamUrl.COMMUNITY_URL}/tradeoffer/{trade_offer_id}/accept'
> >         params = {
> >             'sessionid': session_id,
> >             'tradeofferid': trade_offer_id,
> >             'serverid': '1',
> >             'partner': partner,
> >             'captcha': '',
> >         }
> >         headers = {'Referer': self._get_trade_offer_url(trade_offer_id)}
> > 
> >         response = self._session.post(accept_url, data=params, headers=headers).json()
> >         if response.get('needs_mobile_confirmation', False):
> >             return self._confirm_transaction(trade_offer_id)
> > 
> >         return response
> > 
> > --------------------------------------------------------------------------------------------------------------------------
> > 
> > login.py
> > 
> > def set_sessionid_cookies(self):
> >         community_domain = SteamUrl.COMMUNITY_URL[8:]
> >         store_domain = SteamUrl.STORE_URL[8:]
> >         community_cookie_dic = self.session.cookies.get_dict(domain = community_domain)
> >         store_cookie_dic = self.session.cookies.get_dict(domain = store_domain)
> >         for name in ('steamLoginSecure', 'sessionid', 'steamRefresh_steam', 'steamCountry'):
> >             cookie = self.session.cookies.get_dict()[name]
> >             if name in ["steamLoginSecure"]:
> >                 store_cookie = create_cookie(name, store_cookie_dic[name], store_domain)
> >             else:
> >                 store_cookie = create_cookie(name, cookie, store_domain)
> > 
> >             if name in ["sessionid", "steamLoginSecure"]:
> >                 community_cookie = create_cookie(name, community_cookie_dic[name], community_domain)
> >             else:
> >                 community_cookie = create_cookie(name, cookie, community_domain)
> >             
> >             self.session.cookies.set(**community_cookie)
> >             self.session.cookies.set(**store_cookie)
> > 
> > --------------------------------------------------------------------------------------------------------------------------
> > 
> > market.py
> > 
> > data = {
> >             #'sessionid': self._session.cookies.get_dict("steamcommunity.com")['sessionid'],
> >             'sessionid': self._session_id,
> >             'currency': currency.value,
> >             'appid': game.app_id,
> >             'market_hash_name': market_name,
> >             'price_total': str(Decimal(price_single_item) * Decimal(quantity)),
> >             'quantity': quantity,
> >         }
> > ```
> 
> I have tried it, but it doesn't work

it can't be, I'm using all these fixes right now and right now I have lots on the market quietly.

**Comment by jjh4568520** [comment]
> ```python
> market.py
> ```

I have used all the fixes
can you send me your steampy for emai pls.
896680985@qq.com

**Comment by jjh4568520** [comment]
```python
    def create_buy_order(
        self,
        market_name: str,
        price_single_item: str,
        quantity: int,
        game: GameOptions,
        currency: Currency = Currency.USD,
    ) -> dict:
        data = {
            'sessionid': self._session.cookies.get_dict("steamcommunity.com")['sessionid'],
            'currency': currency.value,
            'appid': game.app_id,
            'market_hash_name': market_name,
            'price_total': str(Decimal(price_single_item) * Decimal(quantity)),
            'quantity': quantity,
        }
        headers = {
            'Referer': f'{SteamUrl.COMMUNITY_URL}/market/listings/{game.app_id}/{urllib.parse.quote(market_name)}'
        }

        response = self._session.post(f'{SteamUrl.COMMUNITY_URL}/market/createbuyorder/', data, headers=headers).json()

        if (success := response.get('success')) != 1:
            raise ApiException(
                f'There was a problem creating the order. Are you using the right currency? success: {success}'
            )

        return response
``` 

working!! 
I have reinstalled steampy and use
```python
client.py

def set_login_cookies(self, cookies: dict) -> None:
        self._session.cookies.update(cookies)
        self.was_login_executed = True
        if self.steam_guard is None:
            self.steam_guard = {'steamid': str(self.get_steam_id())}
        self.market._set_login_executed(self.steam_guard, self._get_session_id())


 @login_required
    def accept_trade_offer(self, trade_offer_id: str) -> dict:
        trade = self.get_trade_offer(trade_offer_id)
        trade_offer_state = TradeOfferState(trade['response']['offer']['trade_offer_state'])
        if trade_offer_state is not TradeOfferState.Active:
            raise ApiException(f'Invalid trade offer state: {trade_offer_state.name} ({trade_offer_state.value})')

        partner = self._fetch_trade_partner_id(trade_offer_id)
        session_id = self._session.cookies.get_dict("steamcommunity.com")['sessionid']
        accept_url = f'{SteamUrl.COMMUNITY_URL}/tradeoffer/{trade_offer_id}/accept'
        params = {
            'sessionid': session_id,
            'tradeofferid': trade_offer_id,
            'serverid': '1',
            'partner': partner,
            'captcha': '',
        }
        headers = {'Referer': self._get_trade_offer_url(trade_offer_id)}

        response = self._session.post(accept_url, data=params, headers=headers).json()
        if response.get('needs_mobile_confirmation', False):
            return self._confirm_transaction(trade_offer_id)

        return response

--------------------------------------------------------------------------------------------------------------------------

login.py

def set_sessionid_cookies(self):
        community_domain = SteamUrl.COMMUNITY_URL[8:]
        store_domain = SteamUrl.STORE_URL[8:]
        community_cookie_dic = self.session.cookies.get_dict(domain = community_domain)
        store_cookie_dic = self.session.cookies.get_dict(domain = store_domain)
        for name in ('steamLoginSecure', 'sessionid', 'steamRefresh_steam', 'steamCountry'):
            cookie = self.session.cookies.get_dict()[name]
            if name in ["steamLoginSecure"]:
                store_cookie = create_cookie(name, store_cookie_dic[name], store_domain)
            else:
                store_cookie = create_cookie(name, cookie, store_domain)

            if name in ["sessionid", "steamLoginSecure"]:
                community_cookie = create_cookie(name, community_cookie_dic[name], community_domain)
            else:
                community_cookie = create_cookie(name, cookie, community_domain)
            
            self.session.cookies.set(**community_cookie)
            self.session.cookies.set(**store_cookie)

--------------------------------------------------------------------------------------------------------------------------

market.py

data = {
           'sessionid': self._session.cookies.get_dict("steamcommunity.com")['sessionid'],     #<<-------------------!!!!!!!!!!!!!!!!!
            'currency': currency.value,
            'appid': game.app_id,
            'market_hash_name': market_name,
            'price_total': str(Decimal(price_single_item) * Decimal(quantity)),
            'quantity': quantity,
        }
```

**Comment by Proborder** [comment]
I use the buy_item function with these fixes and get the error

>There was a problem buying this item. Message: There was a problem purchasing your item. The listing may have been removed. Refresh the page and try again.

create_buy_order work, but buy_item does not :(
Maybe you have some solution to this?
