### ISSUE TITLE
get_trade_offer by trade_offer_id not working anymore

### ISSUE THREAD

**Issue by VlexWest** [bukson/steampy#386]
Hey guys,

do some1 know a fix for `get_trade_offer(trade_offer_id=...)`?
Since 1-2 days it's returning an empty response.

Appreciate any help.

steampy/client.py
![Bild1](https://github.com/bukson/steampy/assets/59747331/5f3548e5-c1cd-43ae-9f97-949d70679b20)

**Comment by lspeed-v** [comment]
Hey, please read previous issues topics. Fixes are already there. https://github.com/bukson/steampy/issues/382#issuecomment-2036162567
https://github.com/bukson/steampy/issues/385#issuecomment-2039923688
