### ISSUE TITLE
How to keep cookies valid for a long time

### ISSUE THREAD

**Issue by boylfunc** [bukson/steampy#404]
When I log in for the first time, I save the cookie.
The second time I log in directly with the last saved cookie, it doesn't work.

I copied the steam cookie in the chrome browser to the code, and it works normally.

This problem has been bothering me for too long.

**Comment by boylfunc** [comment]
Solved, completely rewrite the login module

**Comment by zxzhang8** [comment]
> Solved, completely rewrite the login module

Hi, I have the same question, how do you solve this? Specially, which part of the login module should I rewrite?

**Comment by hunzzz1** [comment]
> > Solved, completely rewrite the login module
> 
> Hi, I have the same question, how do you solve this? Specially, which part of the login module should I rewrite?

To be precise, you probably didn’t obtain the correct cookie

**Comment by hunzzz1** [comment]
> > Solved, completely rewrite the login module
> 
> Hi, I have the same question, how do you solve this? Specially, which part of the login module should I rewrite?

Create login parameters using protobuf
