### ISSUE TITLE
Steam Guard Path Location?

### ISSUE THREAD

**Issue by Koncealed** [bukson/steampy#44]
Can you show us where the location is. Is it the SSFN file? I can't seem to find the file.
also
SteamClient(apikey) conflicts with another Python steam api. http://steam.readthedocs.io/en/latest/intro.html

**Comment by bukson** [comment]
In documentation in Usage section there are 2 ways of obtaining steamguard file, read them.

The conflict can be resolved by 
```using steampy.SteamClient(apikey) ```
instead of
``` SteamClient(apikey)```
