### ISSUE TITLE
Change GameOptions enum to normal class

### ISSUE THREAD

**Issue by Zwork101** [bukson/steampy#48]
So, I'm trying to get my steam backpack. It's one of those sub-inventory backpacks, so I have the context_id = '6'
```python
>>>GameOptions('753','6')
```
But I get the error:
```python
Traceback (most recent call last):
  File "<pyshell#19>", line 1, in <module>
    steam = GameOptions('753','6')
  File "C:\Users\Zwork101\AppData\Local\Programs\Python\Python36-32\lib\enum.py", line 293, in __call__
    return cls._create_(value, names, module=module, qualname=qualname, type=type, start=start)
  File "C:\Users\Zwork101\AppData\Local\Programs\Python\Python36-32\lib\enum.py", line 378, in _create_
    _, first_enum = cls._get_mixins_(bases)
  File "C:\Users\Zwork101\AppData\Local\Programs\Python\Python36-32\lib\enum.py", line 436, in _get_mixins_
    raise TypeError("Cannot extend enumerations")
TypeError: Cannot extend enumerations
```

I don't see what i'm doing wrong, help?

**Comment by bukson** [comment]
As it seems you cannot extend enum (GameOptions is an enum) for your custom purpouse. 

Simple workaround is to make another GameOptions entry (edit it locally)

More complicated is make appropriate pull request.

Btw what game is it?

**Comment by Zwork101** [comment]
It's steam, so I assumed that would have already been on there. I'll prbly make a pull request

**Comment by Zwork101** [comment]
Um, so there just tuples? So, they wouldn't this be working? the context and app id are correct

**Comment by bukson** [comment]
perhaps search in google for TypeError("Cannot extend enumerations")

**Comment by Zwork101** [comment]
Hmm, should this be fixed? I mean, it worked when I added the tuple

**Comment by bukson** [comment]
Fixed and deployed
