### ISSUE TITLE
Is make offer working?

### ISSUE THREAD

**Issue by Zwork101** [bukson/steampy#51]
So, I have the following code to send and offer:
```python
print(itemList)
print([gems])
print(str(friend.steam_id))
steam_client.make_offer(itemList,[gems],str(friend.steam_id))
friend.send_message("Alrighty! Sending your trade right now!")
print("sent trade offer!")
```
And it returns this:
```python
[<steampy.client.Asset object at 0x039B7AB0>, <steampy.client.Asset object at 0x03A2D590>, <steampy.client.Asset object at 0x04868E50>, <steampy.client.Asset object at 0x0489A310>, <steampy.client.Asset object at 0x0489A130>, <steampy.client.Asset object at 0x0489A1B0>, <steampy.client.Asset object at 0x0489A350>, <steampy.client.Asset object at 0x0489A1D0>, <steampy.client.Asset object at 0x05AE3930>, <steampy.client.Asset object at 0x0489A330>, <steampy.client.Asset object at 0x05AE3B90>, <steampy.client.Asset object at 0x05AE39D0>, <steampy.client.Asset object at 0x05AE3710>, <steampy.client.Asset object at 0x05AE3BB0>, <steampy.client.Asset object at 0x05AE32F0>, <steampy.client.Asset object at 0x05AE3050>, <steampy.client.Asset object at 0x05AE3810>, <steampy.client.Asset object at 0x05AE3C70>, <steampy.client.Asset object at 0x05AE3910>, <steampy.client.Asset object at 0x05AE3A90>, <steampy.client.Asset object at 0x05AE3AB0>]
[<steampy.client.Asset object at 0x04868FB0>]
76561198269569899
sent trade offer!
```
However, it does not, infact, end up sending the offer, and raises no errors. Is this something that is known, or have I done something incorrect?

**Comment by Zwork101** [comment]
Ok, I figured it out, there's a trade limit that I prbly should have been aware of. It would be nice if this raised an error?

**Comment by bukson** [comment]
Yes pls, could you send more data, wher it occurs what is the message, what is the limit etc.

**Comment by Zwork101** [comment]
Well, to answer one of those questions, nothing does occur, nothing is raised, and nothing happens on steam. It just ends up with nothing happening.

**Comment by Zwork101** [comment]
Also, according to a quick google search, steam doesn't have a trade limit, so this must be some sort of bug. I'll be looking further into this soon.

**Comment by bukson** [comment]
Strange today when i was testing make_offer didnt work, only make_offer_url, anybody can confirm?
