### ISSUE TITLE
accepting offer with giving items

### ISSUE THREAD

**Issue by LonnikV6** [bukson/steampy#52]
Can\`t accept offer where i giving some items to another person. Problem is _get_confirmations method, when it\`s try to _fetch_confirmations_page it gets steam page with alert instead of valid confirmation page

**Comment by bukson** [comment]
But when you giving items you don't accept, the second party does, are you sure you are doing everythink ok?

**Comment by lonewolf95** [comment]
i meant when i accepting offer where i will give items to someone, like offers from opskins or other trade places

**Comment by bukson** [comment]
what is the alert

**Comment by lonewolf95** [comment]
"Oh nooooooes!
There was a problem loading the confirmations page. Please try your request again later."

**Comment by LonnikV6** [comment]
sorry, it is similar that problem was in my part, i used another acc and there everything was okay. In my main acc still have invalid result from _fetch_confirmations_page, are you interested to know what is reason if i`ll find problem?

**Comment by bukson** [comment]
Yes please :)

**Comment by LonnikV6** [comment]
Problem was on steam part, i compared requests from both accs and when i saw it is equals i just revoked my api key and created it once more to another domain name, after it everything is going all right, sorry for bother you

**Comment by Zwork101** [comment]
Also, unrelated, but I wasn't sure if github was telling you about this: Can you check out my pull request @bukson? Just want to make sure you know I've added some changes

**Comment by bukson** [comment]
Yes i will look at it.

Please excuse me for i have some issues with my master thesis and master project so i have a time for answering the supports and bugfixes but very little for development, please forgive me in few weeks it gets better

**Comment by Zwork101** [comment]
I totally understand, I just wanted to make sure you knew :D
