### ISSUE TITLE
steamguard path question.

### ISSUE THREAD

**Issue by Koncealed** [bukson/steampy#55]
Hello, I am trying to run the steampy storehouse, and I am getting these errors.

https://gist.github.com/anonymous/2711956d6f1b1758cb5a77339cd1307b

I only copied and pasted your code in the storehouse.py

https://gist.github.com/anonymous/6827d53f1439a9149afbb0850c7c9a53

How can I fix these errors. 

Inside the file it looks like this
https://gyazo.com/b7baa7ccf5b3b57eb1505ed7eab28900
. I know how to get Shared Secret and Identity secret, but I get the same error.

**Comment by bukson** [comment]
It looks like some strange encoding error, probably due to using windows. Maybe try to create new txt file in sublime text or some nice editor, set encosing to utf-8, paste data and look if it works

**Comment by Koncealed** [comment]
@bukson Yeah I tried both of that a few minutes ago, it's not working either.

Question in the docs. It says if you have both the shared secret, and the identity secret. Place it in the Steamguard.txt . Where is the Steamguard.txt, or do I create it?

**Comment by Zwork101** [comment]
My advice, go into the source an d quickly specify the encoding, which should be UTF-8. Where is says `open("filepath","type")` add a `encoding="UTF-8"` to it, and it should work.

**Comment by bukson** [comment]
@Koncealed you have to create it manually if you have both secrets but not the file

**Comment by Zwork101** [comment]
Also, try this: http://stackoverflow.com/questions/2276200/changing-default-encoding-of-python

**Comment by Koncealed** [comment]
@bukson I got it to work with the Steamguard. Also if I may you might want to change this in the docs.

Steamguard.txt should be Steamguard.json (Dosen't work with .txt)
Also the link to get the Steamguardfile is no longer working, and it's hard to see your shared secret with out this program http://www.icopybot.com/plist-editor.htm ,and changing the extension to .plist.

**Comment by bukson** [comment]
Nice to know, but are you sure it doesn't work with .txt, you are first person to write this.

I will look into documentation change.

**Comment by Zwork101** [comment]
Looking at the code, it should work perfectly fine with any type of file.
