### ISSUE TITLE
Masters degree

### ISSUE THREAD

**Issue by bukson** [bukson/steampy#56]
Hi.

I am finishing my masters degree and have not so much time for steampy. It will change soon, now I will try to answert support questions, but development and code review will be done after 2 weeks.

Sorry for inconvinience.

I will close this issue when i finish my masters degree program

**Comment by Zwork101** [comment]
Alright, good luck! And if you mind me asking, Masters in what?

**Comment by bukson** [comment]
Computer science :)

**Comment by Zwork101** [comment]
Noice :D
