### ISSUE TITLE
get_my_inventory() not working

### ISSUE THREAD

**Issue by Koncealed** [bukson/steampy#57]
This for example. print(client.get_my_inventory(game=GameOptions.CS))

Does not work at all

Error here https://gist.github.com/anonymous/fb97e97a6c644676744fcff85499b73e

**Comment by bukson** [comment]
Can you show all code?

**Comment by Koncealed** [comment]
https://gist.github.com/anonymous/92c4ac0a647b10fe926e121b51b37609
@bukson

**Comment by Zwork101** [comment]
Is it still not working? Like have you tested it now right now?

**Comment by Koncealed** [comment]
@Zwork101 

[![https://gyazo.com/f028629189ae366f997000aaf60c5e67](https://gyazo.com/f028629189ae366f997000aaf60c5e67/raw)](https://gyazo.com/f028629189ae366f997000aaf60c5e67)

**Comment by Zwork101** [comment]
Just wanted to make sure. The steam API was having some issues recently. Looks like steam isn't responding to the request. Not sure why that's so. Why do you need your inventory in a donation bot anyways?

**Comment by Koncealed** [comment]
@Zwork101 

Was just using the Example as a reference.

**Comment by Zwork101** [comment]
Alright, that makes sense. I'll look into this further

**Comment by MichaelPak** [comment]
I had the same problem. This occurs when the client has not yet created an inventory. Inventory is created when the user has an item. Try to transfer any item to this client.

**Comment by Koncealed** [comment]
@MichaelPak It has multiple items. This Inventory function worked like once or twice, and hasn't worked since.
