### ISSUE TITLE
New version 0.40!

### ISSUE THREAD

**Issue by bukson** [bukson/steampy#59]
This versions add Ermans implementation of steam market api.

It is still a bit experimental so use it carefully. please inform me about issues/bugs that can occur.

This change brakes backawards compatibility, i am aware that this is young library and i can happen, To version 1.0 it can happen some times, I will try to avoid it if possible.

**Comment by bukson** [comment]
Anybody using this new market feature? Some feedback will be nice

**Comment by vasia123** [comment]
`create_sell_order` works pretty well. But price must not include fee, and this not mentioned in docs. Fee calculation method would be nice as a future request.
