### ISSUE TITLE
login problem

### ISSUE THREAD

**Issue by Roomboy2** [bukson/steampy#60]
use SDA as from it to get files, try maFaile does not work

**Comment by Roomboy2** [comment]
from steampy.client import SteamClient
from steampy.market import SteamMarket
from steampy.utils import GameOptions


steam_client = SteamClient('asdfasdfasdfasdfsdf')
steam_client.login('asdfsdfasdfasdfasdf', 'sadfasdfas343', 'nimk86rus/Steamguard.maFile')
is_session_alive = steam_client.is_session_alive()

game = GameOptions.CS
assetid = '10559329008'
money_to_receive = '9,94'

SteamMarket(is_session_alive).create_sell_order(assetid, game, money_to_receive)


this code for the sale of the subject does not work

**Comment by Zwork101** [comment]
So, are you having issues selling something, or login in?

**Comment by Roomboy2** [comment]
steampy.exceptions.LoginRequired: Use login method first on SteamClient

 I think this is due to the fact that not properly indicated steam guard file. I simple indicated maFile from SDA

**Comment by Roomboy2** [comment]
maFile are correct, 100%

![ghgh](https://user-images.githubusercontent.com/26115298/26992010-1a1b3cfa-4d76-11e7-9627-0dd2248d4ef3.jpg)

**Comment by Zwork101** [comment]
No, you don't link the maFile directly. Take the id and secrets and put them into a file with this formatting
```json
{
    "steamid": "YOUR_STEAM_ID_64",
    "shared_secret": "YOUR_SHARED_SECRET",
    "identity_secret": "YOUR_IDENTITY_SECRET",
}
```

**Comment by Roomboy2** [comment]
so I too tried, does not work, please show your example

**Comment by ThreadShakur** [comment]
Dude just create file guard.json near you script and put this there
```
{
    "steamid": "YOUR_STEAM_ID_64",
    "shared_secret": "YOUR_SHARED_SECRET",
    "identity_secret": "YOUR_IDENTITY_SECRET",
}
```
