### ISSUE TITLE
Bad practice with generate_one_time_code

### ISSUE THREAD

**Issue by MichaelPak** [bukson/steampy#64]
Not so long ago, I came across the fact that with two-factor authentication comes empty response (#53). It turned out that if you authorize the client several times without restarting application, the same one-time code will be generated. It's a bad idea to pass a variable like `time.time()` to the default value:

```
def generate_one_time_code(shared_secret: str, timestamp: int = int(time.time())) -> str:
    # generating one-time code
```
Probably, it should look like this:

```
def generate_one_time_code(shared_secret: str, timestamp: int = 0) -> str:
    if not timestamp:
        timestamp = int(time.time())
    # generating one-time code
```

**Comment by crey4fun** [comment]
You saved my life!
I'm currently creating a service with multiple steam bots. A bot getting logged in as soon as a user requests it but since the app could already be running for some minutes or hours, the login fails with the error "Invalid Credentials". I think this bug is also caused by the generate_one_time_code method.

**Comment by MichaelPak** [comment]
@crey4fun the same

**Comment by MichaelPak** [comment]
@bukson can you add me as contributor? At the moment, I'm developing a fairly complex system using your library. I am ready to support and improve this project.

**Comment by bukson** [comment]
Hmm sure but you can contribute anyway :) please start with pull request with this fix. It is really my fault.

**Comment by bukson** [comment]
or it is critical i will do it now

**Comment by bukson** [comment]
Already on master, much much thanks!

**Comment by bukson** [comment]
@MichaelPak a help would be nice in some module for messaging and communication :)
