### ISSUE TITLE
needs_mobile_confirmation

### ISSUE THREAD

**Issue by Roomboy2** [bukson/steampy#66]
![wn8gqsyt4fs](https://user-images.githubusercontent.com/26115298/28489706-5c755dd2-6ee2-11e7-8d02-d2149363ee30.jpg)

**Comment by bukson** [comment]
Ok i see, thanks for your input, could you make a breakpoint in line 69 of market.py or just print the response there.

@Ermans could you help, you wrote this part and you should know what was the expected answer

**Comment by Roomboy2** [comment]
NameError: name, 'response' is not defined

**Comment by bukson** [comment]
Change 

response = self._session.post(SteamUrl.COMMUNITY_URL + "/market/sellitem/", data, headers=headers).json()

to

response = self._session.post(SteamUrl.COMMUNITY_URL + "/market/sellitem/", data, headers=headers).json()
print(response)

**Comment by Ermans** [comment]
The problem is that "price" is the price without any comma or dot, just the whole price in cents.
Example:
if I want to have a 54.64 € gain from the order i must write 5464 in the price field.
I think it should be an int, I don't know why i put it as a string :/

**Comment by Roomboy2** [comment]
@Ermans what can I do if I have RUB?

**Comment by Ermans** [comment]
Try to sell an useless object for an high price (just to be safe) like 10000 and watch on steam the price.

**Comment by Roomboy2** [comment]
![ozxnqjlspz8](https://user-images.githubusercontent.com/26115298/28492103-192f2f2e-6f16-11e7-9f22-dfc0ec540ccb.jpg)
@Ermans

**Comment by Roomboy2** [comment]
all found the error, thanks

**Comment by Ermans** [comment]
That is another problem, we talked about that here https://github.com/bukson/steampy/issues/35
Basically if you use your real phone and the library sometimes you will not see some confirmations, a quick fix is to call it another time when that error raises.

**Comment by Roomboy2** [comment]
how can see the balance

**Comment by Ermans** [comment]
Now is not implemented, but if you want a fast solution:
`from steampy.utils import text_between

text = steam_client._session.get("http://store.steampowered.com/about/").text
balance = text_between(text, 'href="https://store.steampowered.com/account/store_transactions/">', "</a>")`

**Comment by Roomboy2** [comment]
![wrlcjnjxrve](https://user-images.githubusercontent.com/26115298/28492771-c31273c8-6f22-11e7-81a3-783db8469ae5.jpg)
@Ermans where can I see the error

**Comment by Ermans** [comment]
**There is your password and your username on the screen, be care!**

InvalidCredentials happens:
- when you insert wrong credentials
- when you log in too many time in a short period of time

There should be a message but if steam responds with no message, no message will be displayed when the exception occurs.
