### ISSUE TITLE
How to trade the same items?

### ISSUE THREAD

**Issue by Dave-Pham** [bukson/steampy#71]
Pardon me if the question is noobish. I've been testing trading the same set of items between two accounts. I've found that the key of an inventory entry doesn't always match up with its id and both of these fields can change after a trade. Is there a field that uniquely identifies an item and persists after trading?

**Comment by Ermans** [comment]
There is a good talk about it here https://www.reddit.com/r/SteamBot/comments/394o9d/understanding_item_ids/

**Comment by Ermans** [comment]
Also the new endpoint to get the inventories (see here https://stackoverflow.com/questions/17393099/getting-someones-steam-inventory) doesn't have the entry keys anymore.

**Comment by Dave-Pham** [comment]
Thanks for the reading links. I'm just using market names now since it's not guaranteed assetid (aka id) persists.

**Comment by crey4fun** [comment]
Well it said that you can get a receipt with all the new IDs.
Is an implementation for them in steampy already?

**Comment by Ermans** [comment]
@crey4fun What do you mean with receipt?

**Comment by crey4fun** [comment]
From first reddit link:
> You can read the trade offer receipt and get the new asset id and all that other good stuff. Some trade libraries have a method that does exactly that already implemented.

But I don't think it is implemented in steampy yet.

**Comment by vasia123** [comment]
@Ermans He mean https://steamcommunity.com/trade/TRADE_OFFER_ID/receipt

**Comment by crey4fun** [comment]
@vasia123 and how can I use this? When I put in a trade id, I just get "Unable to retrieve trade data"

**Comment by vasia123** [comment]
@crey4fun Yes. My bad. This is not trade_d. Its receipt_id or smth. For example for trade_id 2365030714 i have receipt_id 1837884999305321028.

**Comment by crey4fun** [comment]
Alright, this works. I will implement the trade receipts and create a pull request.

**Comment by bukson** [comment]
If you see value in this make pull request and add market method for fetching receipt and maybe show me where this receipt_id is returned so i can add it to documentation

**Comment by crey4fun** [comment]
@bukson It's not for the market, it is for trades.
When you get the json information about a trade, it will give you a "tradeofferid" and a "tradeid". "tradeid" is the id for receipts.

**Comment by bukson** [comment]
Ok.

**Comment by bukson** [comment]
It is already on master, will deploy it today
