### ISSUE TITLE
Error 26 trade

### ISSUE THREAD

**Issue by ThreadShakur** [bukson/steampy#75]
Hi, anyone can tell me when assetid on  items change? I know that when trade succesful - steam change assetid, when its heppens too? My site often get 26 error, i think it's for assetid

**Comment by crey4fun** [comment]
You should not store the AssetID of your items since they can theoretically change at any time.

**Comment by ThreadShakur** [comment]
I need to store it and i need reasons, when assetid change

**Comment by Ermans** [comment]
Also it changes when you create a sell order (only the ones guard-confirmed). So if you put for sale an item and cancel the order, the assetid changes.
