### ISSUE TITLE
Accept trade offer issue

### ISSUE THREAD

**Issue by Zwork101** [bukson/steampy#77]
I'm trying to accept a trade offer, but suddenly I'm getting
```python
    cli_obj.accept_trade_offer(id)
  File "C:\Users\Zwork101\AppData\Local\Programs\Python\Python36-32\lib\site-packages\steampy\client.py", line 22, in func_wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\Zwork101\AppData\Local\Programs\Python\Python36-32\lib\site-packages\steampy\client.py", line 146, in accept_trade_offer
    partner = self._fetch_trade_partner_id(trade_offer_id)
  File "C:\Users\Zwork101\AppData\Local\Programs\Python\Python36-32\lib\site-packages\steampy\client.py", line 165, in _fetch_trade_partner_id
    return text_between(offer_response_text, "var g_ulTradePartnerSteamID = '", "';")
  File "C:\Users\Zwork101\AppData\Local\Programs\Python\Python36-32\lib\site-packages\steampy\utils.py", line 12, in text_between
    start = text.index(begin) + len(begin)
ValueError: substring not found
``` 
Is this a steam error? I haven't had this problem before. I'm using the correct trade ID I believe, the ID from 
```python
            for trade in trades['response']['trade_offers_sent']:
                trade_id = trade['tradeofferid']
```
With `trades` being client.get_trade_offers(). And I doing somthing wrong?

**Comment by bukson** [comment]
Is that ocuring on all acceptations?

**Comment by Zwork101** [comment]
Currently, yes

**Comment by crey4fun** [comment]
Die you Check the trade offer state?

**Comment by Zwork101** [comment]
yes, it would appear that the items became unavailable, sorry, I didn't check. Would it be wise to raise a custom exception for no?

**Comment by bukson** [comment]
Yep that is nice proposition :) I approve please submit pull request.

Something like: ApiException(Cannot Accept an item with <<STATE OF ITEM>> State)

**Comment by Zwork101** [comment]
Alrighty

**Comment by Zwork101** [comment]
Getting the trade offer state might not be necessary. How about just, "Unable to accept trade at current state"

**Comment by bukson** [comment]
For me ok, would like some opinion of other users :) It sucks guys because pypi has no stats and i don't know if somebody uses this library

**Comment by Zwork101** [comment]
You're the only working python 3 steam trade lib, I'm sure people do

**Comment by Ermans** [comment]
We could put directly the error message raised by steam inside the ApiException
like this one https://steamcommunity.com/tradeoffer/2314835564/ 
or the one which says "This trade offer is no longer valid.". 
All inside _fetch_trade_partner_id() where there is something similar https://github.com/bukson/steampy/blob/c1097f452fe623e90570c176dedca8a8df63463f/steampy/client.py#L167-L172 (line 170)

**Comment by bukson** [comment]
It is a good idea.

Maybe some other ideas where some good exception should be thrown instead of generic python error?

Somebody wrote on reddit "Is there a better library Steampy that would make a Python steambot easier?" so probably i should make it more user friendly, though I presumed that clear documentation and code should be sufficient

**Comment by Ermans** [comment]
A good additions would be to make it "event based" like Flask where you put a decorators on methods when some events occur (ex: when I receive an offer or when an offer changes state), but it's a lot of works.

**Comment by Zwork101** [comment]
Yeah, just like how the "steam" python library works.

**Comment by bukson** [comment]
I meant to develop library not framework :(

**Comment by bukson** [comment]
It sounds like framework

**Comment by Ermans** [comment]
No problem, maybe a proper wiki with some good examples makes everthing easier

**Comment by crey4fun** [comment]
I am a fan of classes for everything since IDEs can tell you then all the attributes you can read and change.
Using classes instead of dicts would be more beginner friendly I think..

So maybe we can create classes for everything (keep backwards compatibitly but deprecate it).

**Comment by bukson** [comment]
Ok i am fun of named tuples myself, i think it works similar way.

I could think of parsing respones of steam into named tuples or classes, its good idea :)

**Comment by Zwork101** [comment]
I also like that idea. Make sure we include a __dict__ attribute, that includes the raw response. Otherwise, that would be a great feature

**Comment by ThreadShakur** [comment]
Dude it meanc that your steam session died, relogin and it would be ok( i got this error, when my session die )

**Comment by Zwork101** [comment]
Wait, really? oh, ok
