### ISSUE TITLE
[Request] Log in a site using "Sign in through Steam"

### ISSUE THREAD

**Issue by Ermans** [bukson/steampy#8]
Is it possible to add the possibility to login in a site through the green button "Sign in through  Steam" and keep the session? Because I need to log in a site that uses SteamIDs.

Some example:
backpack.tf
dota2lounge.com
lootmarket.com

I really want to make some requests to these sites but I need a session but don't know how to do it.

**Comment by bukson** [comment]
Hey Eermans

I would happily help you but i dont understand 100% what you need.

Do you want to take session from browser and use it in steampy or do you want to log in using steampy and then use some session cookies in browser?

**Comment by Ermans** [comment]
I want to be able to do some web call from python to some websites that uses steam openID, so these web call are restricted to user who logged in with steam. I just want to be able to log in to these sites from python with steampy. In browser it's easy I just press the green botton, I log in and Steam handle everything.
Thanks for your time :)

**Comment by ThreadShakur** [comment]
You can enter through the browser , take out the cookies and send together with these cookies , because of the authorization information is there

**Comment by Ermans** [comment]
Oh I didn't think about that, because I was looking for a script-only solution but this is a good workaround because those cookies expire in a long time, so I just need to copy them one time.
Thanks!
