### ISSUE TITLE
Storehouse example does not pick up any trade offers. 

### ISSUE THREAD

**Issue by jman005** [bukson/steampy#81]
I tested the storehouse example, however it seems to not pick up any trade offers. I sent the bot one case, and after waiting a few minutes found it didn't accept it. I tried printing out the offers variable to see if it was picking it up but thinking it wasn't a donation, but it just gave me an empty list. Any solutions?

**Comment by bukson** [comment]
Hi, I would try to run it myself and see if it works :)

**Comment by jman005** [comment]
As in run it with a different account?

**Comment by jman005** [comment]
Looks like the issue is that received offers are in the sent offers category. I'll make a new issue.
