### ISSUE TITLE
Is it possible to login without Steam Guard file?

### ISSUE THREAD

**Issue by droblue** [bukson/steampy#83]
How could I just input the steam guard code to login instead of getting the steam guard file?

**Comment by ThreadShakur** [comment]
This info exist in test or readme in this repo

**Comment by bukson** [comment]
No not really. You can log in via string representing steam guard file, but you need the secrets to create one.

This library is fully automated and this scenario isn't supported, sorry.

**Comment by Zwork101** [comment]
Well, while not directly supported by the library, it is possible. You can get the session through the LoginExecutor, and you can supply that class the one_time_code. Then, create a SteamClient object, and set _session to the session LoginExecutor, and then change has_logged_in (or whatever the name of that variable is) to true
