### ISSUE TITLE
Error 26

### ISSUE THREAD

**Issue by d0geda** [bukson/steampy#85]
Hey guys, as response I am getting just error 26. When I am using SteamGuard file. Anybody can help?

**Comment by Zwork101** [comment]
Can you be more specific? Like, whats the traceback?

**Comment by Ermans** [comment]
Error 26 means that the assetid is not valid.
Specifically when you call [client.make_offer](https://github.com/bukson/steampy/blob/c1097f452fe623e90570c176dedca8a8df63463f/steampy/client.py#L190) be sure to pass a valid list of [Asset](https://github.com/bukson/steampy/blob/c1097f452fe623e90570c176dedca8a8df63463f/steampy/models.py#L17).

**Comment by d0geda** [comment]
@Ermans Exactly! Thank you!!!
