### ISSUE TITLE
Grabbing trade offers from my main account instead of bot account.

### ISSUE THREAD

**Issue by dyc3** [bukson/steampy#86]
I can't get my bot's trade offers. Instead, `get_trade_offers()` and `get_trade_offers_summary()` grabs my main account's trade offers.

- Running Ubuntu 16.04.
- Python 3.5.2
- Logged in to my **main** account on steamcommunity.com in chromium.
- Logged in to my **main** account on the steam application.
- Logged in to my **bot** account on steamcommunity,com in firefox.
- Logged in to my **bot** account using steampy.

I suspect that `urllib` or `requests` is sharing cookies with either the steam application, or chromium.

Here is my `pip freeze`:
```
beautifulsoup4==4.6.0
certifi==2017.7.27.1
chardet==3.0.4
coloredlogs==7.3
humanfriendly==4.4.1
idna==2.6
pyasn1==0.3.6
requests==2.18.4
rsa==3.4.2
steampy==0.44
urllib3==1.22
```

**Comment by Zwork101** [comment]
Your prbly using your main account's API key

**Comment by dyc3** [comment]
You're right, I was using my main account's key. Switched to my bot's API key and it works. Thanks.
