### ISSUE TITLE
there is no feature to send trade offers to non friends via trade url ?

### ISSUE THREAD

**Issue by VVILD** [bukson/steampy#9]
the make trade offer doesnt have any parameter for sending trade offers to non friends via trade url ?

**Comment by VVILD** [comment]
i think i know how to fix this . shall i make a pull request ?

**Comment by VVILD** [comment]
also no feature to know escrow duration of the second party.

**Comment by bukson** [comment]
Ok make pull request, i am on vacations and can look as it/fix it on monday

22.09.2016 11:28 AM "sargun singh gulati" <notifications@github.com>
napisał(a):

**Comment by bukson** [comment]
Solved
