### ISSUE TITLE
All offers returned are sent by the bot. 

### ISSUE THREAD

**Issue by jman005** [bukson/steampy#92]
Using get_trade_offers, for some odd reason all of the offers sent by other users come up in the trade_offers_sent category of the dict, and cannot be accepted. Is this an error with the API itself?

**Comment by Zwork101** [comment]
I had this happen before. Your putting in the wrong API key for steam. I was confused to :P

**Comment by jman005** [comment]
Ohhhhhhhhhh never knew API keys were directly linked to accounts! Thanks so much.
